### ISSUE TITLE
Allow GET requests in TwoFactorProvider::requestAuthenticationCode

### ISSUE THREAD

**Issue by Alsciende** [scheb/two-factor-bundle#10]
Thank you for your bundle, it's very useful and very easy to customize.

However, I'm using your Email Provider and I need to insert into the email an url that authenticates the user by sending the _auth_code parameter. I can't do this right now because the bundle is restricting the allowed methods to 'POST'.

One easy solution is to add a configuration parameter `allow_get_request` that default to `false`.

What do you think? Is it something you will consider if I send a PR?

**Comment by scheb** [comment]
Latest release should do the job.

**Comment by Alsciende** [comment]
Can you clarify, please? I see that release 1.3.1 is headlined "Authentication code accepted via GET", but I don't see how to do it. TwoFactorProvider::requestAuthenticationCode only processes the request if its method is POST.

Besides, between 1.3.0 and 1.3.1, the only commit doesn't look like it is related to the subject: 783e39d6f3aded56bb26ce8607ec6640952ef4e7.

I'm probably mistaken, but I don't see how the GET requests works.

**Comment by scheb** [comment]
My fault, seems like sometjhing went wrong with the push. I'll fix that and let you know when it's done.

**Comment by scheb** [comment]
Re-published that release, now includes the commit that was missing before.

**Comment by scheb** [comment]
I guess this one can be closed now.
