### ISSUE TITLE
Q: Symfony Flex and Symfony 4 Support

### ISSUE THREAD

**Issue by kironet** [scheb/two-factor-bundle#100]
Hey,

this is really useful bundle. 
Are you planing to support Symfony Flex and Symfony 4?

**Comment by scheb** [comment]
I haven't developed on Symfony for quite a while now. What needs to be done to make it compatible with Symfony Flex? Do you know any good resources about it?

**Comment by cordoval** [comment]
I think symfony will support regular configuration bundles so no need for this imo 👎

**Comment by Spomky** [comment]
@kironet there is no change to do here.
You can submit a new package on https://github.com/symfony/recipes-contrib

**Comment by xabbuh** [comment]
Well, you may want to declare compatibility with 4.0 versions of the Symfony components you depend on.

**Comment by cordoval** [comment]
why the bundle has to declare compatibility, @Spomky says there is no change here, wtf?

**Comment by Spomky** [comment]
The question is about Symfony Flex support, not Symfony 4 support.

**Comment by eman1986** [comment]
From what I seen, you just need to whip up a manifest.json file and that should be all you need to do.

I'm using flex at the moment for a new project.

**Comment by kironet** [comment]
Sorry, yeah I've meant to add it here https://github.com/symfony/recipes-contrib
And of course, Symfony 4 will be out soon so it will be nice to make it compatible with 4.0.

**Comment by xabbuh** [comment]
@Spomky @cordoval You are both right. Technically, just to support Symfony Flex there is nothing to do here (in case there is no sensible default configuration that could be shipped for the user). However, since most users will probably start using Flex with Symfony 4 declaring compatibility with Symfony 4 would be a good move forward. But that could as well be part of a separate issue.

**Comment by cordoval** [comment]
i changed my mind 👍 i am up for this change, just because there may be some changes that in symfony4.0 are needed like constraints on composer.json, going to work on a PR, please help me @xabbuh or surpass me by sending a PR, but either way i just want to help 👴

**Comment by cordoval** [comment]
addressing in https://github.com/scheb/two-factor-bundle/pull/102

**Comment by cordoval** [comment]
notice we don't necessarily need a recipe, i think we shouldn't force it, bundles are open and they not need to necessarily coerce usage. So just updating it to symfony 4.0 is fine.

**Comment by cordoval** [comment]
@scheb it can be closed now i guess
