### ISSUE TITLE
Checking that auth is successful and testing on local server?

### ISSUE THREAD

**Issue by VelMrnk** [scheb/two-factor-bundle#103]
Hi. Thank you for your bundle, its very usefull and easy to setup. But I have a couple questions:

1. Is it possible to check google 2fa code before saving a secret code in a model? Like if user will scan qr-code, type google code in a first time and if it is correct, we can save it. How can I validate this google code first time, using your bundle?

2. Is it possible to test it on a local server? For google 2fa I have security key, but when I scan qr code I see message: "Invalid barcode.". Is it because I am trying to scan it from local server?

**Comment by scheb** [comment]
1) You can use the `scheb_two_factor.security.google.google_code_validator` service (which maps to `Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Google\Validation\GoogleCodeValidator`) to check an authentication code.

2) Authentication also works on a local server. Must be a different reason why the bar-code isn't working.

**Comment by scheb** [comment]
@VelMrnk Any update on this? Can this issue be closed?

**Comment by VelMrnk** [comment]
@scheb Yes, it works as you said. Thank you.
