### ISSUE TITLE
Not redirect to two factor Authentication page

### ISSUE THREAD

**Issue by ms8779** [scheb/two-factor-bundle#104]
I configure my symfony app as in doc. But on login it does nothing. User directly login to account without any two factor Authentication.
I am not too much expert in symfony. May be there is some thing in configuration which not mentioned in doc and assumed. I want to use it for google two Factor Authentication.

**Comment by ms8779** [comment]
I am not too much expert in symfony. May be there there is some thing in configuration which not mentioned in doc and assumed. I want to use it for google two Factor Authentication.

**Comment by scheb** [comment]
Did you implement `Scheb\TwoFactorBundle\Model\Google\TwoFactorInterface`in your user entity and does it return a secret code from the `getGoogleAuthenticatorSecret` method?

**Comment by ms8779** [comment]
Yes I did. I think there is some problem with config may be. Does I have to config any listener for it?
Here is that user entity 
class User implements TwoFactorInterface, UserInterface  {

        /**
         * @ORM\Column(name="googleAuthenticatorSecret", type="string", nullable=true)
         */
        private $googleAuthenticatorSecret;

        // [...]

        public function getGoogleAuthenticatorSecret()
        {
            return $this->googleAuthenticatorSecret;
        }

        public function setGoogleAuthenticatorSecret($googleAuthenticatorSecret)
        {
            $this->googleAuthenticatorSecret = $googleAuthenticatorSecret;
        }

    	/**
     	 * @ORM\Id;
     	 * @ORM\Column(type="integer")
     	 * @ORM\GeneratedValue(strategy="AUTO")
     	 */
    	protected $id;
.........................

**Comment by scheb** [comment]
Listeners will be automatically registered.

The model looks good to me. And I guess you also have a secret code configured for that user.

Another thing could be that you have to configure a different authentication token class. By default the bundle triggers only for the `Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken` authentication token, which is used by Symfony's default user+passwort authentication. If you're using a special bundle for authentication it could be that would have to configure the token class of that bundle.

**Comment by ms8779** [comment]
`security:
    access_decision_manager:
        strategy: unanimous
    encoders:
        AppBundle\Entity\User: sha1

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_users:
            entity: { class: AppBundle:User, property: username }
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            remember_me:
                secret: '%secret%'
            guard:
                authenticators:
                    - app.form_login_authenticator
            logout:
                path: /logout
                target: /
            # activate different ways to authenticate

            #http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/member, roles: [ROLE_USER, IS_FULLY_AUTHENTICATED] }
        - { path: ^/demi-god-mode, roles: [ROLE_ADMIN, IS_FULLY_AUTHENTICATED] }
        - { path: ^/god-mode, roles: [ROLE_SUPER_ADMIN, IS_FULLY_AUTHENTICATED] }
`
This is mine security config.
Guide me please. Because I did not developed this app. I have assigned to integrate just google two factor with this bundle.
Thanks Respected

**Comment by scheb** [comment]
So I see that your app is using some custom-crafted authentication component. Did you check which token class is used after logging in? You can see that from the developer tool bar. If it's not the default one `Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken`, you have to register the other one in the bundle's configuration.

**Comment by ms8779** [comment]
Thanks. This my service file. Can you help me from it. because my dev toolbar is not working.
`# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.form_login_authenticator:
        class: AppBundle\Security\FormLoginAuthenticator
        arguments: ["@router", "@security.password_encoder"]
        
    app.timeline_format:
        class: AppBundle\Service\TimelineService
        arguments: ["@doctrine.orm.entity_manager"]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]`

**Comment by ms8779** [comment]
Also here is my configuration for bundle now. It is ok

```
scheb_two_factor:
    google:
        enabled: true
    security_tokens:
        - AppBundle\Security\FormLoginAuthenticator
```

**Comment by ms8779** [comment]
Thanks. It works. My app was using
security_tokens:
        - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken

**Comment by umpirsky** [comment]
Happened to me, why isn't this added to default config?

**Comment by scheb** [comment]
Because it's a BC break. Applications would silently have another token class configured that triggers two-factor authentication.

It's mentioned in the installation instructions that you have to configure the token when using a guard-based authentication provider: https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/installation.md#step-5-configure-authentication-tokens

**Comment by umpirsky** [comment]
Oh, OK. Thanks.
