### ISSUE TITLE
Insecure transmission of secret to domain outside control of owners

### ISSUE THREAD

**Issue by martinwithaar** [scheb/two-factor-bundle#106]
Having looked through your code I saw that in order to generate the QR code the TOTP secret is sent to a Google service. I'd like to point out that this is bad security practice.

I have used the following bundle to make sure the QR code is generated server-side so that the secret is only known to the domain and the individual end-user: https://github.com/endroid/qr-code-bundle

If you like I could make a branch to further integrate this solution into the codebase and send you a merge request.

**Comment by scheb** [comment]
Fair point. I don't consider the QR code a core feature of the bundle, it's more of a nice bonus feature. Therefore I wouldn't want to introduce another dependency for a feature that most people don't use. I'd rather go with a note in the documentation, that the QR code feature is relying on a 3rd party and cross-link the bundle for people who want to generate the code locally.

Do you have a piece of code that I could add as a reference implementation?

**Comment by scheb** [comment]
Added a notice in the documentation, closing this therefore. If you want to share a reference implementation, feel free to add it here or open a PR.
