### ISSUE TITLE
Providers are always called

### ISSUE THREAD

**Issue by i3or1s** [scheb/two-factor-bundle#110]
Hi,

We have been trying to implement new provider. This provider would turn off 2fa in certain cases.

Case: If the user has 2fa on but does not want to be disturbed by it each time on his machine. Google has a similar feature called trusted device.

Now we noticed that no matter what each provider will be called. Meaning only providers that are authenticated won't be called.
What is your take on modifying this to call each active provider and for the first authenticated stop looping?

Also, one more thing here would be adding priority to provider definition.

If this sounds like a reasonable request I would not mind creating a PR.

**Comment by scheb** [comment]
Hello,

did you see that the bundle has a (trusted computer)[https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/trusted_computer.md] feature, to skip 2fa when you're on a trusted device?

If a user has multiple authentication methods enabled, it is actually a feature of the bundle that each authentication method has to be fulfilled when logging in. If you don't want that, make sure that a user can only active a single authentication method in their profile. A missing feature is in fact, that you can have multiple authentication methods active and the user can choose one to complete 2fa. This is something that I plan to add for the next major version, which us currently developed in the 3.x branch.

**Comment by i3or1s** [comment]
@scheb Thank you a lot I did not see the trusted computer feature at all. I will definitely check it out, it might be just what I need.

Keep up the great work and thanks a lot for doing this.

**Comment by i3or1s** [comment]
@scheb I looked at the feature and it is not quite what is needed. As I see trusted filter is the one holding the cookie manager and providers.

Architecture is not flexible enough for me to implement the case. To be more precise with the case. The decision on whether the request is trusted or not can be determined from HTTP headers.

It might be good to abstract this portion of code.

**Comment by scheb** [comment]
Well, then can't you replace the TrustedFilter with your own custom implementation?
