### ISSUE TITLE
[3.x] check Authentication Code

### ISSUE THREAD

**Issue by sebastianblum** [scheb/two-factor-bundle#111]
hello @scheb,

we tried to test and review the 3.x branch and your refactoring using guard.

We don't understand this method:
https://github.com/scheb/two-factor-bundle/blob/3.x/Security/Authentication/Provider/TwoFactorAuthenticationProvider.php#L61
```php
    private function checkAuthenticationCode(TwoFactorToken $token)
    {
        return $token->getCredentials() === '1';
    }
```

Is it correct so?

Thank you very much
Sebastian

**Comment by scheb** [comment]
The branch is work in progress. Checking the authentication code is not implemented yet, so for testing purposes it's accepting "1" as a valid authentication code and that's the line you mentioned. The real implementation of this is one of the next things on the list.

**Comment by sebastianblum** [comment]
Thank you, Ping ne if I can help you

**Comment by scheb** [comment]
@sebastianblum Great, thank you. Would be nice if you could test the upcoming alpha version and give some feedback. As soon as I have working 2fa (not necessary with all features) I'll ping you in #73, which is the main thread for the 3.x refactoring. Would especially be interested if the upgrade instructions are complete.

**Comment by bytehead** [comment]
@scheb same here, I've already started to integrate and test the bundle in 3.x. Looks really promising! Thanks for your work and ping me if you need some support!

**Comment by scheb** [comment]
@sebastianblum @bytehead See #73
