### ISSUE TITLE
Use Google and U2F at the same time

### ISSUE THREAD

**Issue by stephanvierkant** [scheb/two-factor-bundle#112]
I've got a user with both Google Authenticator and a U2F key, but only the Google Authenticator page is showed. I'm using [R\U2FTwoFactorBundle](https://github.com/darookee/u2f-two-factor-bundle).

The 'problem' (or missing feature ;)) is caused by `Security\TwoFactor\Provider\TwoFactorProviderRegistry::requestAuthenticationCode`, which returns a Response as soon as a Provider has been found. So as soon as the Google provider has been found, it won't return the U2F provider.

How can I use two providers (U2F and OTP) at the same time?

Update: sorry, after digging into this, this issue is actually a duplicate of #110.

**Comment by scheb** [comment]
It's a feature of the bundle. When multiple providers are active, all of them need to be fulfilled (one after another).

This behavior will change with the upcoming version 3.x. The new will have an option to configure, if all active providers need to be fulfilled or only one (giving the user the ability to choose, which one).
