### ISSUE TITLE
Trying to generate a secret

### ISSUE THREAD

**Issue by darsh12** [scheb/two-factor-bundle#119]
Hey,
I am trying to just generate a secret code for a user but when I follow the documentation and go to the page it gives me the following error:

`Controller "App\Controller\TwoFactor::index()" requires that you provide a value for the "$twoFactor" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one.`

<h2>TwoFactor.php</h2>

     <?php
    namespace App\Controller;
    use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
    use Symfony\Bundle\FrameworkBundle\Controller\Controller;
    use Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Google\GoogleAuthenticatorInterface;

    class TwoFactor extends Controller
    {

    /**
     * @Route("/google")
     */

    public function index(GoogleAuthenticatorInterface $twoFactor)
    {
        $secret = $twoFactor->generateSecret();

        return $this->render('two_factor/index.html.twig', ["secret" => $secret]);

    }
    }

**Comment by scheb** [comment]
I think we're missing a service definition here to make the auto-wiring work. I need to look into that.

For now I'd suggest to get the `scheb_two_factor.security.google_authenticator` service directly from the container. That should do the job.

**Comment by darsh12** [comment]
Thanks

**Comment by scheb** [comment]
Let's keep that open, until I fixed it ;)

**Comment by darsh12** [comment]
okay

**Comment by scheb** [comment]
3.3.0 now supports auto-wiring.
