### ISSUE TITLE
QR Code Issuer

### ISSUE THREAD

**Issue by hrza** [scheb/two-factor-bundle#12]
Hi, 

Fist, nice work with this bundle, help me a lot :) . I just can't figure out how to add issuer when generating url for QR Code. Is this supported? 

Cheers

**Comment by scheb** [comment]
The bundle uses a method [from a dependency](https://github.com/sonata-project/GoogleAuthenticator/blob/master/lib/GoogleAuthenticator.php#L100). Unfortunateley an issuer is not supported.

I guess I have to implement that part on my own.

**Comment by Spomky** [comment]
Hi,

Let me introduce you [my library](https://github.com/Spomky-Labs/otphp) that supports this feature.
Feel free to contact me if you need help for its implementation on this project.

**Comment by scheb** [comment]
Latest release has a new configuration option for the issuer value.

**Comment by hrza** [comment]
great ! :+1:
