### ISSUE TITLE
Send authentication when needed

### ISSUE THREAD

**Issue by stephanvierkant** [scheb/two-factor-bundle#121]
When the email authentication is enabled an e-mail is sent after login, even if an other authentication method is used. What's the best practice to set up Email (or SMS) as a fallback, i.e. if a user has lost his/her phone?

I only want to send an email/SMS when the user chooses `/2fa?preferProvider=[email|sms]`

**Comment by stephanvierkant** [comment]
I was looking at [this code](https://github.com/scheb/two-factor-bundle/blob/master/Security/TwoFactor/Provider/Email/EmailTwoFactorProvider.php#L29):

    if ($user instanceof TwoFactorInterface && $user->isEmailAuthEnabled()) {
            // Generate and send a new security code
            $this->codeGenerator->generateAndSend($user);
            return true;
        }

I was thinking about wrapping something like: `if ($context->isPreferredProvider()) { }`  around `$this->codeGenerator->generateAndSend()`, to force sending the email only when `email` is the preferred provider, not just one of them.

`$context->isPreferredProvider()` decides if it's the preferred provider, based on the User entity and the Request. If so: send email/sms, if not: just return `true` to return it to `availableTwoFactorProviders`

What do you think?

**Comment by scheb** [comment]
That doesn't work, because if it's not the preferred provider and you're switching to email authentication, the code will never be sent.

**Comment by stephanvierkant** [comment]
When opening `/2fa?preferProvider=email`, the preferred provider is overridden. Why not use the same logic for sending the email?

**Comment by scheb** [comment]
Yes, but `beginAuthentication` is only called once for each two-factor provider, right after the login. It's there to determine which authentication providers are active for the user. When switching the preferred provider, it will not be called again.

**Comment by stephanvierkant** [comment]
Ah, you're right.

We can move sending emails to the  `TwoFactorFormRendererInterface::renderForm` method?

**Comment by scheb** [comment]
Implemented in the 4.x branch.
