### ISSUE TITLE
TwoFactorInterface::getGoogleAuthenticatorSecret() may return null

### ISSUE THREAD

**Issue by frostieDE** [scheb/two-factor-bundle#124]
As stated in the documentation, method `getGoogleAuthenticatorSecret()` of interface `TwoFactorInterface` returns `string|null` but the return type hint only allows `string` to be returned. It needs to be changed to `?string` to allow `null`

**Comment by frostieDE** [comment]
Sorry, did not see that :-)

**Comment by iltar** [comment]
Would it be an option to change the docblock? I don't mind either way, but it's really confusing now

**Comment by frostieDE** [comment]
The docblock might be fixed for the current release, but in future releases, I'd prefer to have `?string` as return type.
