### ISSUE TITLE
setGoogleAuthenticatorSecret can be removed from the interface

### ISSUE THREAD

**Issue by iltar** [scheb/two-factor-bundle#125]
It doesn't seem that `setGoogleAuthenticatorSecret` is used anywhere and removing it won't cause BC breaks. This function might be nice if you've implemented the `UserInterface` on an entity, but even then, the method is not used anywhere, thus has no use in the interface. It now forces me to make my security user mutable, which it should definitely not be. Solved it with this, but is ugly:

```php
    public function setGoogleAuthenticatorSecret(?string $googleAuthenticatorSecret): void
    {
        throw new \BadMethodCallException('Not allowed to change the secret in the user.');
    }
```

**Comment by scheb** [comment]
Removed in v3.4.0

**Comment by iltar** [comment]
Awesome, thanks!
