### ISSUE TITLE
Calling custom routes during two factor authentication

### ISSUE THREAD

**Issue by cfoehrdes** [scheb/two-factor-bundle#126]
We have implemented a custom provider which uses SMS for the two factor authentication.
Now we need to implement a "resend verification code" feature on the 2FA authentication page. This means we have to call a controller which generates a new code and resend it to the user.

The problem is, that the `\Scheb\TwoFactorBundle\Security\Http\Firewall\TwoFactorListener` is redirecting every request to the login page because the current token is a `TwoFactorToken` and we are not doing a call to the `2fa_login_check` route.

Is there a way to call other routes during `IS_AUTHENTICATED_2FA_IN_PROGRESS` state?

**Comment by scheb** [comment]
I think that depends on how you configure your firewall. If you whitelist the route in `access_control` for the `IS_AUTHENTICATED_2FA_IN_PROGRESS` role it should work.

**Comment by iltar** [comment]
I would like to chime in here. SMS (Text messages to phone), are insecure. A lot of providers re-use phone numbers after a while. If you send any information to a phone number of which you cannot verify if the owner is still the same, it might end up at the wrong person.

**Comment by cfoehrdes** [comment]
Thank you for the quick response!

Adding it to `access_control` was the first thing I tried and just checked it again and it does not work. I don't understand which logic should let the request pass if it is in the `access_control`. As the firewall name and the token type `TwoFactorToken` matches the `TwoFactorListener` will always match and redirect to login in https://github.com/scheb/two-factor-bundle/blob/ddce1d6b61e126f0acf1708a15906524e607c04d/Security/Http/Firewall/TwoFactorListener.php#L130-L136

@iltar thanks for your input. We considered this in our discussion about the SMS integration

**Comment by iltar** [comment]
@cfoehrdes did you make sure to register the exceptions _before_ the 2FA in `access_control`? The list is top -> down, when it encounters and matches a specific rule, it will stop after that. If your 2FA rule is hit first, the exception will never be checked after.

**Comment by scheb** [comment]
@cfoehrdes Could you try if `IS_AUTHENTICATED_ANONYMOUSLY` is making the route pass? And as @iltar mentioned, please put it at the very beginning of the `access_control` list. My assumption is that anonymous routes would just passed through the firewall, without hitting the `TwoFactorListener` and force a redirect.

**Comment by cfoehrdes** [comment]
It is the first rule in our `access_control` and i testen both `IS_AUTHENTICATED_2FA_IN_PROGRESS` and `IS_AUTHENTICATED_ANONYMOUSLY`. The request is always hitting the `TwoFactorListener`

**Comment by scheb** [comment]
@cfoehrdes Could you solve the issue? Another potential solution that I've thought about would be to exclude the route in the firewall's path. But I'm not sure about that, could be that you're then missing the session/token when the route is called.

I was actually under the impression, that access_control would allow us to have callable routes within the two-factor process. But seems like the firewall listener is always kicking in, even when the access_control allows that route to be called. If there's no other way, we need to add a condition in the TwoFactorListener to exclude anonymous/2fa_in_progress routes from being redirected.

**Comment by stephanvierkant** [comment]
It can be a solution to #121 as well.

Many sites with 2FA via SMS have a 'send SMS to +xx xx-xxxxxx01'-button before actually sending the SMS. This solves two problems:
1. Don't send an SMS when SMS authentication is enabled, but not the primary method (I prefer U2F if my USB token is plugged in)
2. Verify the correct telephone number before sending an SMS. See https://github.com/scheb/two-factor-bundle/issues/126#issuecomment-382107480

**Comment by cfoehrdes** [comment]
@scheb Could not find a solution yet. I experimented a lot with the firewall and I not find a way to bypass the Listener. We also thought about placing the route outside the firewall, but then we would not have the current user to get the the information where to send the SMS from.

**Comment by scheb** [comment]
Please check out v3.6.0. The `TwoFactorListener` class now takes the `access_control` configuration into account and lets those paths through, which are configured `IS_AUTHENTICATED_ANONYMOUSLY` or `IS_AUTHENTICATED_2FA_IN_PROGRESS`.

**Comment by cfoehrdes** [comment]
Thank you @scheb !
