### ISSUE TITLE
TwoFactorListener fails on different firewall with shared context

### ISSUE THREAD

**Issue by iltar** [scheb/two-factor-bundle#131]
In my firewall config, I have dozens of firewalls. A bunch of them use the same firewall context (secured_area). Due to them having a different entry point, I can't put them under the same firewall but they _can_ share context. Example: my `oauth` firewall has `secured_area` as context, because that's what the user will log into. However, the `TwoFactorListener` receives the firewall name as `secured_area`, while my `TwoFactorToken` receives `oauth` as provider key. Both are correct, so this check fails, as `'secured_area' !== 'oauth'`: https://github.com/scheb/two-factor-bundle/blob/5c192efa30765c74289ce28bcd01d614c0edb426/Security/Http/Firewall/TwoFactorListener.php#L115-L120

On success my oauth redirects to `/`, which needs full authentication. The redirect causes the `secured_area` `start()` to trigger, which causes a redirect to `/login/`. Once on login, the 2fa isn't triggered due to this check failing and keeps infinitely redirecting to `/login/`.

Instead of injecting the firewall name into the `TwoFactorListener`, perhaps we can inject the `FirewallContext` or `FirewallConfig`? The firewall config `name` is the provider key of the token, while it still knows about the firewall `context`: `secured_area`.

```
FirewallConfig {#4901 ▼
  -name: "oauth"
  -userChecker: "App\Component\Security\Authentication\CustomerPortal\UserChecker"
  -requestMatcher: "security.request_matcher.dTUycd2"
  -securityEnabled: true
  -stateless: false
  -provider: "App\Component\Security\Authentication\CustomerPortal\UserProvider"
  -context: "secured_area"
  -entryPoint: "App\Component\Security\Authentication\Oauth\Authenticator"
  -accessDeniedHandler: null
  -accessDeniedUrl: null
  -listeners: array:2 [▶]
  -switchUser: null
}
```

**Comment by scheb** [comment]
I tried to reproduce, but could not. The `TwoFactorListener` always received the firewall name and not the context value and I also could not find a code path in the `SecurityExtension` of the security bundle, which would pass the context value instead of the firewall name.

Could it be that you have - besides the context value being "secured_area" - also have a firewall named "secured_area" in your config? Would be great if you could post how your config looks like.

**Comment by scheb** [comment]
Closed due to inactivity.
