### ISSUE TITLE
Support php 7.2

### ISSUE THREAD

**Issue by TheRatG** [scheb/two-factor-bundle#132]
Support php 7.2

**Comment by scheb** [comment]
I don't see an issue here. Both 2.x and 3.x are building on PHP 7.2.

**Comment by TheRatG** [comment]
@scheb this is part in composer.json from master
    "require": {
            "php": "^7.1.3",

**Comment by scheb** [comment]
That version constraint allows all PHP versions `>= 7.1.3` and `< 8.0` release. That's what the `^` symbol is doing. See Composer version constraints for details: https://getcomposer.org/doc/articles/versions.md#caret-version-range-
