### ISSUE TITLE
It's hard to override AuthenticationContext

### ISSUE THREAD

**Issue by umpirsky** [scheb/two-factor-bundle#134]
Since it's hardcoded in https://github.com/scheb/two-factor-bundle/blob/master/Resources/config/two_factor.xml#L9.

Not only that, I need to inject some services into my `AuthenticationContext`, which is not possible since it's not a service.

**Comment by umpirsky** [comment]
I ended up overriding factory. Not that hard actually.

**Comment by scheb** [comment]
That's actually the intended solution for this specially if you need to inject additional things into the context object ;)
