### ISSUE TITLE
Error: A void function must not return a value

### ISSUE THREAD

**Issue by ultramegatom** [scheb/two-factor-bundle#136]
After adding the Bundle i get the following error: ```Fatal error: A void function must not return a value in /home/hiprotec/www/var/cache/dev/ContainerXduqtcg/TrustedCookieResponseListener_c7f9b85.php on line 30```

Symfony seems to add a return within the built container:
```
public function onKernelResponse(\Symfony\Component\HttpKernel\Event\FilterResponseEvent $event) : void
    {
        $this->initializerc7f9b85 && ($this->initializerc7f9b85->__invoke($valueHolderc7f9b85, $this, 'onKernelResponse', array('event' => $event), $this->initializerc7f9b85) || 1) && $this->valueHolderc7f9b85 = $valueHolderc7f9b85;

        return $this->valueHolderc7f9b85->onKernelResponse($event);
    } 
```

The problematic methods are: 
onKernelResponse in https://github.com/scheb/two-factor-bundle/blob/master/Security/TwoFactor/Trusted/TrustedCookieResponseListener.php#L49

addTrustedToken in https://github.com/scheb/two-factor-bundle/blob/master/Security/TwoFactor/Trusted/TrustedDeviceTokenStorage.php#L78

If i remove the 2 void return types it seems to work fine. Is this a bug / compability issue with my symfony version?

symfony: 3.4.10
php: 7.2.3

**Comment by scheb** [comment]
I see you're using the lazy-loading feature, which is provided by ocramius/proxy-manager. I don't really think this is an issue of the two-factor bundle, more of an issue how these proxy methods are generated and the fact, that they're generating a return statement even for void methods. Are you running on the latest version of ocramius/proxy-manager? If that doesn't change anything it's likely to be a bug in Symfony.

**Comment by ultramegatom** [comment]
I updated the package ocramius/proxy-manager to 2.1.1 (was 2.0.4) everything seems to work fine now.

Thank you very much for your help.

**Comment by scheb** [comment]
Great  :thumbsup:
