### ISSUE TITLE
integrate latest two factor bundle with lastest fos user bundle

### ISSUE THREAD

**Issue by kricha** [scheb/two-factor-bundle#139]
Hello, is there any simple way to integrate these two bundles? I'm trying to do it with default instruction, but seems fos skip two factor listeners

**Comment by scheb** [comment]
Should actually work, the bundle doesn't really care where authentication is coming from. First thing to check: Which token class does the FOS bundle provide after successful login? You might need to register that token in the [configuration](https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/configuration.md) if it's not the default one: `Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken`.

**Comment by kricha** [comment]
@scheb it provides Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken this token

**Comment by scheb** [comment]
Ok, that looks fine. Do you have at least one of the TwoFactorInterfaces implemented and `isEmailAuthEnabled` / `isGoogleAuthenticatorEnabled` returns true for that user?

And would you please post you security config?

**Comment by kricha** [comment]
@scheb , sorry, my docker ip was whitelisted in parameters.yml. All works great. Thanks.
