### ISSUE TITLE
Ability to enter code manually 

### ISSUE THREAD

**Issue by arksnorman** [scheb/two-factor-bundle#140]
Allow users to enter the code manually if for some reason they are unable to scan the qr image with their scans

**Comment by arksnorman** [comment]
You mean the secret code.

**Comment by arksnorman** [comment]
Is it safe to give it to user

**Comment by scheb** [comment]
Doesn't matter. Either you display the code directly to the user, or you show them the QR code. There's no difference. The code is also in the QR code, so you could decode the plain-test code from it.

When it comes to security, you should make sure you're exposing the secret/qr code only to the user and you should use a safe channel like HTTPS.

**Comment by arksnorman** [comment]
Oooh okay. Thanks

**Comment by stephanvierkant** [comment]
I've seen a team using a shared account with 2FA and they shared the password and the code using (the same) password manager, effectively killing the whole idea of multi factor. In fact, the secret code is just another password.
