### ISSUE TITLE
Stateless integration

### ISSUE THREAD

**Issue by MichaelKubovic** [scheb/two-factor-bundle#141]
Hello, we have a stateless api built around Symfony Security Bundle that serves other applications as an authentication service. We use `UsernamePasswordJsonAuthenticationListener` (`json_login`) firewall that uses same `UsernamePasswordToken` as `form_login`. I'm using the latest released version (3.2.6).

There are a few issues I'd need a little help with:

My initial problem is that authentication is not halted by 2fa, but it probably should, otherwise I get success response (output from controller login action, or lexik's jwt success handler, doesn't matter). The initial auth request with valid credentials passes through, even though I receive email with generated Authentication code. I'd expect it to fail with 401/WWW-Authenticate. I've tried to track down where is the code that actually redirects user to `auth_form_path`, but I only found `DefaultAuthenticationFailureHandler` which seems to do just that, except it seems to be triggered by auth failure.

The whole flow should look like this:

```
+---------+                                                                          +-------+
| Client  |                                                                          | Auth  |
+---------+                                                                          +-------+
     |                                                                                   |
     | POST /api/authenticate username=michael password=test                             |
     |---------------------------------------------------------------------------------->|
     |                                                                                   |
     |     401 Unauthorized, WWW-Authenticate: 2fa_email, Location: /api/2fa?token=abcde |
     |<----------------------------------------------------------------------------------|
     |                                                                                   |
     | POST /api/2fa?token=abcde code=123456                                             |
     |---------------------------------------------------------------------------------->|
     |                                                                                   |
     |                                                                   200, token: ... |
     |<----------------------------------------------------------------------------------|
     |                                                                                   |
```

I'm also looking for a bit of advice on approach to make it work. I'd like to use tokens between requests to avoid cookies/sessions. So here is the list of things that I though I'd need to extend, but I'm struggling with.

- custom response when 2fa kicks in, indicating 2fa provider and token for the next request
- override `FormController` to handle Json requests
- somehow load `TwoFactorToken` based on ?token url param

Thanks.

**Comment by scheb** [comment]
I don't think this would work with the bundle. One of the basic concepts of the bundle is that you have a decorated authentication token after the initial login. One that is hiding the given permissions and that can be used to detect that you're currently in an intermediate authentication state and two-factor authentication has not been completed.

In a stateless environment this concept doesn't work any more, because the token is not persisted and will be gone on the next request. So you're basically starting again from the beginning. To be honest, I have no idea how to make this work.

**Comment by MichaelKubovic** [comment]
One thing I don't understand is why my request initial login request is halted here https://github.com/scheb/two-factor-bundle/blob/master/Security/Http/Firewall/TwoFactorListener.php#L149 instead of https://github.com/scheb/two-factor-bundle/blob/master/Security/Http/Firewall/TwoFactorListener.php#L153.

As I understand, authentication decorator intercepts form_login, and wraps authenticated token into TwoFactorToken. Next TwoFactorListener should redirected me to form, but instead it just returns. And because there isn't any other firewall listener configured, it just falls into controller configured for that 2fa login form.

**Comment by MichaelKubovic** [comment]
Apart from that, I was able to achieve what I need and I'd like to contribute a PR with extension points and/or configuration to support this case. Basically I'd like to hook in three places.

### 1) Return custom response instead of displaying form to indicate a need for 2fa

Ideal solution would be a custom form renderer, it has all the information needed to produce nice response. However because of above issue I propose having an option to decide how to respond instead of letting route pass. Something along these lines:
```php
if ($this->twoFactorRequiredListener) {
    $this->twoFactorRequiredListener->onTwoFactorRequired($event, $currentToken, $this->options);
    // both $currentToken and options could be retrieved through container, just the event is mandatory argument
}
```
before this `return` https://github.com/scheb/two-factor-bundle/blob/master/Security/Http/Firewall/TwoFactorListener.php#L149

### 2) Pickup 2nd request and restore authenticated token

Ideal solution would be having `CurrentTokenProvider`, with default implementation being `$currentToken = $this->tokenStorage->getToken();`. I could overwrite it and use my own mechanism to construct `TwoFactorToken` token on fresh request, here https://github.com/scheb/two-factor-bundle/blob/master/Security/Http/Firewall/TwoFactorListener.php#L133.

### 3) Add a configuration option for custom success/failure handlers

Should be easily done in a same way as default Symfony firewalls.

**Comment by scheb** [comment]
> One thing I don't understand is why my request initial login request is halted here https://github.com/scheb/two-factor-bundle/blob/master/Security/Http/Firewall/TwoFactorListener.php#L149 instead of https://github.com/scheb/two-factor-bundle/blob/master/Security/Http/Firewall/TwoFactorListener.php#L153.
You can only run into that return statement, if you have a matching path pattern configured in `access_control` and that one allows access to either `IS_AUTHENTICATED_ANONYMOUSLY` or `IS_AUTHENTICATED_2FA_IN_PROGRESS`. In that case the request can pass and deliver its content without being redirected to the two-factor authentication form. This is intended behaviour to make routes accessible during the two-factor authentication phase e.g. to deliver CSS or other kinds of content that needs to be served with a route. Maybe that helps to figure out what's going on.

> As I understand, authentication decorator intercepts form_login, and wraps authenticated token into TwoFactorToken. Next TwoFactorListener should redirected me to form
Until there, that's exactly what's supposed to happen.

**Comment by MichaelKubovic** [comment]
Now when I know how to avoid that condition, I should be able to solve 1) with custom form renderer that returns my custom response. It might need some tweaks here and there, I have not tested it yet through.

2) will be done with custom TokenStorage implementation as you suggested and the

3) no problem there, will be implemented

The project is currently on hold so I might need some more time to get back to it with PR.

**Comment by scheb** [comment]
Ok, great. Take your time, we're not in a hurry ;)

**Comment by scheb** [comment]
Closing. Custom `authentication_required_handler` and the suggestions above would be the way to go.

**Comment by LemosT** [comment]
@MichaelKubovic did you ever get your code to work? I'm in the same situation as you (using 2 factor with lexik JWT), trying to follow in your footsteps.

**Comment by MichaelKubovic** [comment]
Hi, we've moved away from lexik jwt for authentication. But if I remember correctly I had it working with  customizations mentioned above https://github.com/scheb/two-factor-bundle/issues/141#issuecomment-401795787.

**Comment by LemosT** [comment]
Thanks for the quick reply! Any chance you have saved your security.yaml or other configuration file?
