### ISSUE TITLE
Make bundle compatible with symfony2.7

### ISSUE THREAD

**Issue by airoude** [scheb/two-factor-bundle#15]
After upgrading to v2.7 last weekend this bundle started triggering deprecated errors.

```
PHP Deprecated:  Symfony\Component\DependencyInjection\Definition::setFactoryService(doctrine) is deprecated since version 2.6 and will be removed in 3.0. Use Definition::setFactory() instead. in /home/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Definition.php on line 208
PHP Stack trace:
PHP   1. {main}() /home/app/app/console:0
PHP   2. Symfony\Component\Console\Application->run() /home/app/app/console:27
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /home/app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\HttpKernel\Kernel->boot() /home/app/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:70
PHP   5. Symfony\Component\HttpKernel\Kernel->initializeContainer() /home/app/app/bootstrap.php.cache:2396
PHP   6. Symfony\Component\DependencyInjection\ContainerBuilder->compile() /home/app/app/bootstrap.php.cache:2618
PHP   7. Symfony\Component\DependencyInjection\Compiler\Compiler->compile() /home/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:614
PHP   8. Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process() /home/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:117
PHP   9. Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process() /home/app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtensionConfigurationPass.php:39
PHP  10. Scheb\TwoFactorBundle\DependencyInjection\SchebTwoFactorExtension->load() /home/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php:55
PHP  11. Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load() /home/app/vendor/scheb/two-factor-bundle/DependencyInjection/SchebTwoFactorExtension.php:48
PHP  12. Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseDefinitions() /home/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php:58
PHP  13. Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseDefinition() /home/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php:119
PHP  14. Symfony\Component\DependencyInjection\Definition->setFactoryService() /home/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php:153
PHP  15. trigger_error() /home/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Definition.php:208
```

I have pinpointed the issue, it comes from [Resources/config/persistence.xml](https://github.com/scheb/two-factor-bundle/blob/master/Resources/config/persistence.xml#L7-L9).

I've also provided a solution that fixes this deprication warnings.

```xml
<service id="scheb_two_factor.entity_manager" class="Doctrine\ORM\EntityManager" public="false">
    <factory service="doctrine" method="getManager"/>
    <argument>%scheb_two_factor.model_manager_name%</argument>
</service>
```

Cheers!

**Comment by scheb** [comment]
Did you try upgrading `sensio/distribution-bundle`. According to http://knpuniversity.com/blog/upgrading-symfony-2.7#you-need-to-upgrade-sensio-distribution-bundle this will solve the problem.

If this isn't a solution I'll do the change in my bundle.

**Comment by airoude** [comment]
I've tried that, it didn't solve the problem (to bad).

```php
error_reporting(error_reporting() & ~E_USER_DEPRECATED);
```

Could you still make the change please, the errors are killing us since we run CLI the whole day.

**Comment by scheb** [comment]
It definitely needs a little bit more work than that, because the `<factory>` element seems to be introduced in Symfony 2.6, which means I would have to bump the minimum requirement of the bundle to that version.

I'll have to take a look at this tomorrow.

**Comment by scheb** [comment]
I was able to fix the deprecated message which results from the factory configuration. Besides this there are additional deprecated messages from the "security.context" services, which has been replaced with "security.token_storage" and "security.authorization_checker" in 2.6.

To fix the deprecated message I would need to migrate to the token storage, which would require to bump the minimum version to Symfony 2.6. But I'd like to support at least Symfony 2.3+. So basically I have no chance to remove the deprecation AND support older Symfony releases.

Since deprecated messages are not actually an error, I think you should solve the problem by silencing those in your environment. This should be the way to go:
http://stackoverflow.com/questions/28850809/disable-deprecated-warning-in-symfony-2-7/29928561#29928561

**Comment by scheb** [comment]
@airoude Any feedback on this? Did the post on Stackoverflow help?

**Comment by cjgordon** [comment]
Symfony2.7 works fine for me with this bundle, however I'm using MongoDB with custom persistence.

**Comment by airoude** [comment]
@cjgordon [they've silenced](https://github.com/symfony/symfony/commit/73bbaa6cc7d706b0e945107657fbd240efec0c97) the deprecation messages.
@scheb sorry for not responding I haven't received any notifications, symfony actually released a couple of days later a "fix", thanks! Btw isn't it possible to load configs by kernel version? That would put people in position to upgrade to v3.0 or create branches for specific versions?

**Comment by scheb** [comment]
I'm planning to do a 2.0 release of the bundle with all the BC breaks necessary when Symfony 3.0 is released.

**Comment by ismailbaskin** [comment]
ping. SF 3.0 has been released!

**Comment by j0k3r** [comment]
Any news about a the 2.0.0? Do you need help on upgrading to Symfony 3.0?

**Comment by scheb** [comment]
Haven't started with it yet. At my new company we're not using Symfony in day-to-day work, so I'm no longer that deep into the topic. If someone would send me a PR with the changes for Symfony 3, I'd be glad to merge them :)

**Comment by scheb** [comment]
Version 2.0.0 now supports Symfony 2.6 and above.
