### ISSUE TITLE
Correctly display localized authentication errors

### ISSUE THREAD

**Issue by frostieDE** [scheb/two-factor-bundle#156]
In order to display the `authenticationError` correctly, [`InvalidTwoFactorCodeException::getMessageKey()`](two-factor-bundle/Security/Authentication/Exception/InvalidTwoFactorCodeException.php) must return `scheb_two_factor.code_invalid` instead of the actual error message "Invalid two-factor authentication code.".

Afterwards, you can use the following code snippet to properly display authentication errors (which can now also come from an invalid CSRF token):

```
{% if authenticationError %}
    <p>{{ authenticationError|trans(authenticationErrorData) }}</p>
{% endif %}
```

Current values of `authenticationError` variable:

* CSRF Token invalid: "The CSRF token is invalid." (I guess this message key comes from Symfony itself) 
* Invalid 2FA code: "Invalid two-factor authentication code." (This message key is not useful as the provided translation key is `scheb_two_factor.code_invalid`)

**Comment by scheb** [comment]
Fixed for the `InvalidTwoFactorCodeException` The messageKey of the CSRF exception is in fact "The CSRF token is invalid.", that's what the framework provides. So I cannot change this.
