### ISSUE TITLE
Protection against replay attacks

### ISSUE THREAD

**Issue by iluuu1994** [scheb/two-factor-bundle#157]
https://en.wikipedia.org/wiki/Replay_attack

Right now, if someone could obtain a 2FA code that code could be reused until it expires. Caching the used codes of the last few minutes and disallowing repeated usage could help here.

It's not a huge security risk since most websites with security concerns will use HTTPS but still something to consider. The codes could also be obtained in different ways (key loggers for example).

**Comment by iluuu1994** [comment]
I'll give that a try. Thanks!

**Comment by scheb** [comment]
Great, let me know if it works, then I'll add a section to the documentation.

One thing to note: Of course you don't want to hook to the `scheb_two_factor.authentication.failure` event, but to the `scheb_two_factor.authentication.success` event to capture valid two-factor codes.

**Comment by iluuu1994** [comment]
@scheb Works great. You probably meant the `scheb_two_factor.authentication.attempt` event because `scheb_two_factor.authentication.success` is already too late.

**Comment by Spomky** [comment]
May be linked to #77.

**Comment by iluuu1994** [comment]
@scheb Yes in `scheb_two_factor.authentication.attempt`. Theoretically you could enter a not-yet valid token which would make it impossible to use it afterwards. But that seems pretty unlikely so I'll take the change. Tokens are also only cached for 5 minutes so...

```php
<?php

namespace App\EventListener;

use Psr\SimpleCache\CacheInterface;
use Scheb\TwoFactorBundle\Security\TwoFactor\Event\TwoFactorAuthenticationEvent;
use Symfony\Component\Security\Core\Exception\AuthenticationException;

class TwoFactorAuthenticationSuccessListener
{
    /** @var CacheInterface */
    private $cache;

    public function __construct(CacheInterface $cache)
    {
        $this->cache = $cache;
    }

    public function __invoke(TwoFactorAuthenticationEvent $event): void
    {
        $cacheKey = '2fa_used_key_' . $event->getToken()->getCredentials();

        if ($this->cache->has($cacheKey)) {
            throw new AuthenticationException('Cannot reuse token.');
        }

        $this->cache->set($cacheKey, true, new \DateInterval('PT5M'));
    }
}
```

**Comment by iluuu1994** [comment]
The cache should be user-specific by the way. Because theoretically two users could have the same token at the same time. But again the risk is pretty low.
