### ISSUE TITLE
ip and dot-less cookies cannot be global

### ISSUE THREAD

**Issue by zerkms** [scheb/two-factor-bundle#160]
`TrustedCookieResponseListener` currently prepends `.` to every hostname but `localhost`:

```php
            if ('localhost' !== $requestHost) {
                $domain = '.'.$requestHost;
            }
```
It breaks development environments that use ip address or dotless hostnames, like `foo-dev`.

Why is it there after all?

**Comment by scheb** [comment]
Valid point with the IP address, need to change this.

The "." is actually there, to make the cookie available too all sub-domains of that domain. But I actually don't remember the reason for this. Probably because of "www.example.org" vs. "example.org".

**Comment by zerkms** [comment]
> to make the cookie available too all sub-domains of that domain
what if there was an option (probably - enabled by default for BC), that would do that?

I'm not a security expert, but exposing a cookie to sub-domains by default is a potential threat.

**Comment by scheb** [comment]
Bugfix in v3.12.1.

Will change the cookie behavior for 4.x.
