### ISSUE TITLE
Configurable cookie behavior

### ISSUE THREAD

**Issue by scheb** [scheb/two-factor-bundle#161]
Currently the bundle is setting trusted cookies on the domain and it's subdomains. Should become either a configured domain or use the current domain as-is.

**Comment by cfoehrdes** [comment]
We are also experiencing problems with the trusted device feature in combination with single-sign on. As the user is redirected from an other domain in a SAML authentication process the cookie is never picked up with 'lax' or 'strict' setting. The bundle currently does not allow to set e.g. `null` for same site behavior.
Do you have a suggestion for a workaround to get trusted device working in this scenario?

**Comment by scheb** [comment]
>  Do you have a suggestion for a workaround to get trusted device working in this scenario?
Not, but if you send me a PR that would allow setting it explicitly to `null` (while keeping `lax` as the default value), I'd be glad to merge it.

**Comment by cfoehrdes** [comment]
Sure I will create one today

**Comment by scheb** [comment]
Domain setting can be overwritten since d15ae55ad8beda7b69fb43f64e0969dd8ec4412c, which is all needed.
