### ISSUE TITLE
Second factor provider switch

### ISSUE THREAD

**Issue by quentinus95** [scheb/two-factor-bundle#167]
Hi, it's me again.

Does the bundle provides a native way to switch the second factor provider? What I plan to do is displaying a form with the default second factor form for the user, and display some links to switch on another provider if the user cannot perform the second factor with the selected provider (he does not have his U2F key or whatever).

I have written a global service used by each provider to determine if the provider should be used:

```php
public function isAuthenticationRequired($provider, TokenInterface $token)
{
    $user = $token->getUser();
    
    // [...] casting the user to the proper type and doing some defensive checks
    
    if (!$user->getSecondFactor()->supports($provider)) {
        return false;
    }

    $selected = $this->session->get('second_factor', $user->getPreferredTwoFactorProvider());

    return $selected === $provider;
}
```

Now, the main issue I have is: how can I get this to work? Should I write a custom route on a custom controller allowing the role `IS_AUTHENTICATED_2FA_IN_PROGRESS`, set the `second_factor` session key depending on the clicked link, and redirect to the target page? Or is there a "native" way to do it using the bundle?

Thanks!

**Comment by scheb** [comment]
This feature comes out-of-the-box with v3. See [documentation](https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/multi_authentication.md). The [default authentication form template](https://github.com/scheb/two-factor-bundle/blob/master/Resources/views/Authentication/form.html.twig) shows you how to implement the provider switch - by passing the `preferProvider` query parameter.

**Comment by quentinus95** [comment]
Thanks! I saw the `getPreferredTwoFactorProvider` in the documentation but not the ability to pass the `preferProvider` to the login path.
