### ISSUE TITLE
Pass the request object/headers to TrustedComputerInterface.addTrustedComputer

### ISSUE THREAD

**Issue by Alsciende** [scheb/two-factor-bundle#17]
I'd like to store some information about the trusted computer along with the expiration date: User Agent, Client IP Address, Geolocation, etc. For that,  I need the http headers from the request. Could it be possible to pass `$request` or `$request->headers` as a third argument to `addTrustedComputer`?

**Comment by umpirsky** [comment]
This would be useful. :+1:

**Comment by scheb** [comment]
Found a solution that doesn't break, but still is flexible enough. Replace the `scheb_two_factor.trusted_computer_manager` service with your own custom service, which is implementing `Scheb\TwoFactorBundle\Security\TwoFactor\Trusted\TrustedComputerManagerInterface`. When you do that, you no longer need to implement the TrustedComputerInterface into the user entity. Your service has to take care of how to store the trusted strings.

**Comment by umpirsky** [comment]
May be offtopic, but I used to override `RequestListener` and `AuthenticationContext` just to pass instance of `User` model that is not an entity. And noticed that this 2 are not easy to override. `AuthenticationContext` is also instantiated on many places, making bundle harder to override. Factory + interface may help here.
