### ISSUE TITLE
IpWhitelist per user

### ISSUE THREAD

**Issue by th3squal** [scheb/two-factor-bundle#175]
Hi,

Is there a way to give ip whitelist per user, and not only for all users?

Exemple :
- Whitelist XXX.XXX.XXX.XXX for all users
- Whitelist YYY.YYY.YYY.YYY only for user John which work from other office, in addition of common whitelist

I try "custom whitelist provider", but this provider fired only before login event and skip 2FA only if "common" ip is whitelisted.

Thanks!

**Comment by scheb** [comment]
Not sure about the execution order in Symfony internals, but shouldn't you have access to the token (and therefore the user) via token storage, when `getWhitelistedIps` is called?

**Comment by th3squal** [comment]
unfortunately Token seems to be always null.

getWhitelistedIps seems to be called just before returning token.

**Comment by scheb** [comment]
After thinking about this for a while, it would make sense to pass the `AuthenticationContext` (which contains the token, user and more) as an argument to `getWhitelistedIps`. But that would be a BC break, therefore I cannot just implement it into the current version. Would be something for the 4.x branch.

**Comment by th3squal** [comment]
Yes it would make sense, after some try passing AuthenticationContext into getWhitelistedIps do the job.

Do you want a PR to start 4.x branch ? :)

**Comment by scheb** [comment]
PR for 4.x would be great!

**Comment by scheb** [comment]
Merged into 4.x branch. Thanks for your contribution!
