### ISSUE TITLE
Add a symfony recipe

### ISSUE THREAD

**Issue by B-Galati** [scheb/two-factor-bundle#177]
Hello,

I think it would be a nice idea to provide a recipe for this great bundle.

Cheers!

**Comment by scheb** [comment]
https://github.com/symfony/recipes-contrib/pull/307

**Comment by scheb** [comment]
Is there anything that should be set-up by the recipe, something that you're missing?

**Comment by B-Galati** [comment]
I think we could set-up routes and a basic config like mentionned here :
https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/installation.md

**Comment by B-Galati** [comment]
We could also proposed the post guard token as alternative and much more.

**Comment by scheb** [comment]
Hmm, agree that it would make sense for the routes. Will give it another try...

**Comment by B-Galati** [comment]
IMHO, it would make sense to provide a basic config too that works in most cases.

**Comment by scheb** [comment]
Basic config that should work in most cases = empty config ;)

**Comment by scheb** [comment]
Decided to go with the security_tokens configuration (since that's relatively specific to the application) and the routes.

PR: https://github.com/symfony/recipes-contrib/pull/558
