### ISSUE TITLE
Trusted device cookie does not save

### ISSUE THREAD

**Issue by SirWaddles** [scheb/two-factor-bundle#182]
Hi,

I'm using `two-factor-bundle` version v3.16.0, and Symfony 3.4.12.

Whenever I try to use the trusted device cookie, it does not appear to actually send the cookie to the client. In trying to debug this, I found that the `TrustedDeviceTokenStorage` that the `TrustedCookieResponseListener` owns, appears to be a different instance to that of the previously set up one owned by `TrustedDeviceManager`.

Removing `lazy=true` from `trusted_device.xml` in the configuration seems to solve this issue for me.

I've not use lazy loading for services before, so I'm not sure what would be causing this.

Thanks in advance,
Waddles

**Comment by scheb** [comment]
Honestly, no idea. Sounds like an issue with dependency injection to me. I'd recommend to debug when an instance of TrustedDeviceTokenStorage is created. Actually the same service instance should be used in all its use-cases.

**Comment by SirWaddles** [comment]
Oh I see, thanks for finding that.

It looks to be working now.
