### ISSUE TITLE
Google Authenticator: http status 400 (bad request)

### ISSUE THREAD

**Issue by aur1mas** [scheb/two-factor-bundle#19]
Hi,

I've encountered a problem. If I add `qr_code` as suggested in documentation:

```
$url = $container->get("scheb_two_factor.security.google_authenticator")->getUrl($user);
echo '<img src="'.$url.'" />';
```

I get: `400 Bad Request`.

Found solution on stackoverflow: http://stackoverflow.com/questions/17071368/400-bad-request-when-attempting-to-insert-qr-code-image-for-google-authenticator

Maybe we should use *https://chart.googleapis.com* instead of *https://www.google.com*?

**Comment by scheb** [comment]
Changed the domain in the current  v1.4.2 release.
