### ISSUE TITLE
subject auth mail translation

### ISSUE THREAD

**Issue by behalp** [scheb/two-factor-bundle#191]
In this file vendor/scheb/two-factor-bundle/Mailer/AuthCodeMailer.php there is hardcoded EN subject:

`->setSubject('Authentication Code')`

please read there tlanslation from 

vendor/scheb/two-factor-bundle/Resources/translations/messages.XX.yml

files, using scheb_two_factor.auth_code value.

**Comment by scheb** [comment]
The dafault `AuthCodeMailer` is very basic. If you're running a serious website, I'd assume - to change content and style of the the email - that you want to exchange it with a [custom implementation](https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/providers/email.md#custom-mailer) anyways.
