### ISSUE TITLE
2fa not working. 

### ISSUE THREAD

**Issue by faneaatiku** [scheb/two-factor-bundle#197]
I'm struggling to make this bundle to work on a brand new Symfony app. 
I followed every step in the docs but it doesn't seem to work, user is not redirected to the 2fa page at login. 
scheb_two.factor.yaml: 
```scheb_two_factor:
    google:
        enabled: false
    email:
        enabled: true
        digits: 8
        sender_email: no-reply@example.com
        mailer: App\Service\Notification\EmailService
      # Trusted device feature
    trusted_device:
        enabled: false                 # If the trusted device feature should be enabled

    security_tokens:
        - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken
```

security.yaml
```providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            two_factor:
                auth_form_path: 2fa_login    # The route name you have used in the routes.yaml
                check_path: 2fa_login_check  # The route name you have used in the routes.yaml
            anonymous: true
            guard:
                authenticators:
                    - App\Security\AppAuthenticator
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 18000 # 5 hours in seconds
                path:     /
            logout:
                path:   app_logout
            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
```

routes.yaml: 
```
#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_logout:
    path: /logout

2fa_login:
    path: /2fa
    defaults:
        _controller: "scheb_two_factor.form_controller:form"

2fa_login_check:
    path: /2fa_check
```

 App\Security\AppAuthenticator - is a plain simple authenticator made after symfony's documentation : https://symfony.com/doc/current/security/form_login_setup.html

App\Entity\User:

```....
    /**
     * @ORM\Column(name="google_uthenticator_secret", type="string", nullable=true)
     */
    private $googleAuthenticatorSecret;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $authCode;

    /**
     * @var bool
     * @ORM\Column(type="boolean", nullable=true, options={"default": 0})
     */
    private $hasGoogleAuth = false;

    /**
     * @var bool
     * @ORM\Column(type="boolean", nullable=true, options={"default": 1})
     */
    private $hasEmailAuth = true;
.....

    /**
     * Return true if the user should do two-factor authentication.
     *
     * @return bool
     */
    public function isGoogleAuthenticatorEnabled(): bool
    {
        return $this->hasGoogleAuth;
    }

    /**
     * @return bool
     */
    public function isEmailAuthEnabled(): bool
    {
        return $this->hasEmailAuth;
    }

    /**
     * Return the user name.
     *
     * @return string
     */
    public function getGoogleAuthenticatorUsername(): string
    {
        return $this->getEmail();
    }

    /**
     * Return the Google Authenticator secret
     * When an empty string is returned, the Google authentication is disabled.
     *
     * @return string
     */
    public function getGoogleAuthenticatorSecret(): string
    {
        return $this->googleAuthenticatorSecret;
    }

    /**
     * @param string|null $googleAuthenticatorSecret
     * @return User
     */
    public function setGoogleAuthenticatorSecret(?string $googleAuthenticatorSecret): self
    {
        $this->googleAuthenticatorSecret = $googleAuthenticatorSecret;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getAuthCode(): ?string
    {
        return $this->authCode;
    }

    /**
     * @param string $authCode
     * @return User
     */
    public function setAuthCode(?string $authCode): self
    {
        $this->authCode = $authCode;
        return $this;
    }

    /**
     * @return string
     */
    public function getEmailAuthRecipient(): string
    {
        return $this->getEmail();
    }

    /**
     * @return string
     */
    public function getEmailAuthCode(): string
    {
        return $this->authCode;
    }

    /**
     * @param string $authCode
     * @return User
     */
    public function setEmailAuthCode(string $authCode): self
    {
        $this->authCode = $authCode;
        return $this;
    }
```

I can confirm the user I'm testing has $hasEmailAuth = true. 

I'm pretty sure there's something simple I missed. Any ideas?

**Comment by scheb** [comment]
I don't see any obvious mistake. Could you please check if you enter [this method](https://github.com/scheb/two-factor-bundle/blob/2be8d05/Security/Authentication/Provider/AuthenticationProviderDecorator.php#L61) when you do the login?

**Comment by faneaatiku** [comment]
> I don't see any obvious mistake. Could you please check if you enter [this method](https://github.com/scheb/two-factor-bundle/blob/2be8d05/Security/Authentication/Provider/AuthenticationProviderDecorator.php#L61) when you do the login?

Yes, it does.

But in Scheb\TwoFactorBundle\Security\TwoFactor\Handler\TwoFactorProviderHandler::beginTwoFactorAuthentication 
```$activeTwoFactorProviders = $this->getActiveTwoFactorProviders($context);``` is an empty array, thus this method returns return $authenticatedToken; - which is a Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken instance

**Comment by faneaatiku** [comment]
My bad, looks like [this method](https://github.com/scheb/two-factor-bundle/blob/2be8d05b2e46c8e34bd9f596f73c19ca84b2f602/Security/TwoFactor/Provider/Email/EmailTwoFactorProvider.php#L33) returns false.

**Comment by faneaatiku** [comment]
> > I don't see any obvious mistake. Could you please check if you enter [this method](https://github.com/scheb/two-factor-bundle/blob/2be8d05/Security/Authentication/Provider/AuthenticationProviderDecorator.php#L61) when you do the login?
> 
> Yes, it does.
> 
> But in Scheb\TwoFactorBundle\Security\TwoFactor\Handler\TwoFactorProviderHandler::beginTwoFactorAuthentication
> `$activeTwoFactorProviders = $this->getActiveTwoFactorProviders($context);` is an empty array, thus this method returns return $authenticatedToken; - which is a Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken instance

Looks like this method returns false because i didn't implemented both TwoFactorInterface on my User entity. This is why I always chose the exact name for my classes/interfaces. I was pretty sure it's some dumb thing like this. Thanks for the support.

**Comment by faneaatiku** [comment]
also: _security_logout route definition should be placed in the documentation IMHO. When/if you have time for that. found the fix on your blog https://www.christianscheb.de/archives/331 in the second comment.

**Comment by scheb** [comment]
Glad it works for you now. Regarding the logout route you're not the first person running into this issue. I'll add #198 when I find some time.
