### ISSUE TITLE
Google Provider deprecation

### ISSUE THREAD

**Issue by tony-tran** [scheb/two-factor-bundle#200]
Hi,

As you can see here : https://developers.google.com/chart/infographics/docs/qr_codes
The API is deprecated and turn off since March 14, 2019.

This line : https://github.com/scheb/two-factor-bundle/blob/master/Security/TwoFactor/Provider/Google/GoogleAuthenticator.php#L42
doesn't work now.

Do you have a solution to use your bundle ? 
I can contribute to your project if you have any idea.

**Comment by scheb** [comment]
I'd rather remove it from the bundle, because it not necessary as a feature and [as pointed out in the documentation](https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/providers/google.md#qr-codes) it's not such a great idea anyways to send sensible data over to a Google service.

**Comment by scheb** [comment]
Now removed in 4.x.
