### ISSUE TITLE
Allow user to cancel the 2FA process.

### ISSUE THREAD

**Issue by glennthehuman** [scheb/two-factor-bundle#203]
Allow the user to go back to the login page.
Currently, if we initially logged-in (thereby 2FA process was started), we cannot go back to the log-in page to use a different account. Even if we directly input the path for {{ path("security_logout") }}, e.g. "/logout", we are just redirected back to "/2fa". We are "trapped" at the token input form.

**Comment by scheb** [comment]
Please make sure you have the logout route whitelisted for anonymous access in the `access_control` configuration:

```yaml
    access_control:
        - { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        ...
```

**Comment by glennthehuman** [comment]
got it! Thank you.
