### ISSUE TITLE
Preparation step not triggered

### ISSUE THREAD

**Issue by scheb** [scheb/two-factor-bundle#212]
**Bundle version**: 4.x
**Symfony version**: any

**Description**
When the login redirects directly to the 2fa form, the provider method `prepareAuthentication()` and event `TwoFactorAuthenticationEvents::REQUIRE` are never triggered. This is only executed when the bundle force-redirects to the 2fa form.

For the email provider this means, an authentication code is not generated and no email is sent.

**Workaround**
On login, redirect to a page that requires a fully authenticated user.

If you don't need lazy prepartion of the two-factor providers you can also use the 3.x version of the bundle.

**Comment by scheb** [comment]
**Warning**:

For two-factor providers that _must_ execute the `prepareAuthentication()` method, this may be an security issue.

For example, the email provider generates & persists a new code only when that method is triggered. That means, if someone knows the previous email authentication code, they could avoid to trigger the `prepareAuthentication()` method to keep the previous code valid and send that one over to pass two-factor authentication.

**Comment by soullivaneuh** [comment]
I'm not sure to understand the workaround. If I change the other method link to a random page requiring login, the page will just redirect the 2fa and force the preferred provider, am I right? 

In that case, how this workaround can solve the issue? :thinking:

**Comment by soullivaneuh** [comment]
Also, do you have any clue about how to fix it? May we help?

**Comment by soullivaneuh** [comment]
Ok I understood the way to go, but I see two issues here:

1. How sall I redirect to a random page after the provider selection? With a JS trick?
2. When I click on a page that requires authentication, a new mail is sent by the provider. If I click again, an another mail with an another code is sent. And over and over... I'm not sure it's the intended solution, is it?

Regards

**Comment by scheb** [comment]
Yes, that's less than ideal. If you want to use two-factor authentication via email, I'd suggest to stick with 3.x for now.

**Comment by soullivaneuh** [comment]
@scheb Thanks, I think I'll take a look at that.

 Does the 3.x version "fix" also the second issue about infinite code generation/send?

**Comment by scheb** [comment]
Yes, 3.x doesn't have that issue, but it has a different disadvantage. If you have multiple two-factor providers enabled and you require only one of them being fulfilled (multi-factor is disabled), then the email code will always be sent even when it's not the selected two-factor provider.

If that's not an issue for you or you can live with it, go with 3.x.

**Comment by soullivaneuh** [comment]
> then the email code will always be sent even when it's not the selected two-factor provider.

Hmm, will it be the case for the custom provider too or it is just concerning email?

Because I especially use the `PreferredProviderInterface` to not send an SMS to the customer at each validation, unless he asks for it. :-)

**Comment by soullivaneuh** [comment]
I opened an issue for the other use case: #223 :+1:

**Comment by scheb** [comment]
> Hmm, will it be the case for the custom provider too or it is just concerning email?
> Because I especially use the PreferredProviderInterface to not send an SMS to the customer at each validation, unless he asks for it. :-)

Unfortunately, with 3.x the preparation step will be executed for all two-factor providers that the user has enabled. So if the user has SMS and email authentication available, but only needs to pass one (no multi-factor authentication), both the SMS and the email will be sent out right after the login.

This is not ideal, as I understand. It is the reason why the separate preparation step was introduced with 4.x.

**Comment by soullivaneuh** [comment]
Ok, but in that case I don't understand one thing: What is the point of `PreferredProviderInterface` in 3.x?

**Comment by scheb** [comment]
It defines the default (preferred) provider for each user. The one the system will always ask for primarly. The user can still choose to use a different provider, if needed.

The drawback of 3.x is/was, that it always prepares all available providers right from the start, even when they're not needed.

**Comment by soullivaneuh** [comment]
Hi @scheb,

I'm curious, why a major target as it's a bug?

Thanks

**Comment by scheb** [comment]
The solution that I have right now would require to change the `TwoFactorTokenInterface` which is considered as an extension point, so I cannot just change that within the 4.x branch.

**Comment by soullivaneuh** [comment]
I found an another solution: https://github.com/scheb/two-factor-bundle/pull/226

Don't know if it's acceptable, but it does not require a new major IMO. :+1:

**Comment by scheb** [comment]
Considered that solution too, but I found the other one way cleaner.

We should not be afraid of releasing major versions. Traditionally, there's this huge respect everyone has when it comes to a new major version. Everyone has the expectation that it is a big update with many breaking changes, taking a long time till it's ready. That's something everyone learned over the years. Doesn't need to be, there's no reason major versions need to be scary. In semantic versioning it's just a mechanic to keep people from upgrading automatically into these versions and unintentionally introducing breaking changes. What I want to say is, it's fine to release major versions, even doing that regularly as long as the upgrade path is clear. Honestly, I was thinking about releasing that change within the 4.x version because the change would probably affect no one, but it did not feel right, since it's an official extension point and for that one person who implemented their own TwoFactorToken it would actually matter.

**Comment by soullivaneuh** [comment]
@scheb I'm not against new major at all, I was just curious. :+1: 

However, #226 is here and working (AFAIK). Merge and release it as a patch would unlock the situation waiting the cleaner way on 5.x, except you are going to release 5.x soon?

What do you think?

At least, a review of #226 to be sure it's reliable would be greatly appreciated, if you have some time! :+1:

**Comment by scheb** [comment]
Cannot tell when I'm done with the proper 5.x changes. I'm doing this stuff after work, when I find some time and motivation. I pushed my [WIP 5.x branch](https://github.com/scheb/two-factor-bundle/tree/fix-preparation) and left some comments on your PR.

How should we proceed? Finish the 4.x patch (as you proposed, using session) or fix it with 5.x? Any help appreciated.

**Comment by soullivaneuh** [comment]
I totally understand about time, no worry. :+1: 

As #226 is functional, I would suggest push it as patch on 4.x waiting your better implementation.

I will update the MR according to your review ASAP! :+1:

**Comment by scheb** [comment]
New release 4.7.0 fixes this issue.

**Comment by Jalliuz** [comment]
I had the same problem by trying to connect a PWA to our Symfony application with 2FA. So also an API call actually. It worked with scheb/two-factor-bundle version 3 but now we upgraded Symfony to 4.4 and we also upgraded to scheb/2fa bundle and the problem appeared.

**I fixed it with a listener, so in services.yml**
```yml
UserBundle\Listener\TwoFactorApiRouteListener:
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
```

**And then the listener:**
```php
<?php

namespace UserBundle\Listener;

use Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorToken;
use Symfony\Component\Security\Http\Event\InteractiveLoginEvent;

class TwoFactorApiRouteListener
{
    /**
     * @param InteractiveLoginEvent $event
     */
    public function onSecurityInteractiveLogin(InteractiveLoginEvent $event)
    {
        /**
         * This is a fix for the Scheb 2FA bundle in combination with a API call to the 2FA route (e.g. the PWA)
         *
         * The error: 'The two-factor provider "%s" has not been prepared.'
         *
         * The available providers are only prepared "onKernelResponse"
         * But an API user does a single request, so the providers are not prepared yet
         */
        $token = $event->getAuthenticationToken();

        // Replace "api_login_2fa_check" with your own route
        if (
            $event->getRequest()->get('_route') === 'api_login_2fa_check' &&
            $token instanceof TwoFactorToken
        ) {
            $token->setTwoFactorProviderPrepared('google');
            $token->setTwoFactorProviderPrepared('email');
            $token->setTwoFactorProviderPrepared('totp');
        }
    }
}
```
