### ISSUE TITLE
Can I specify several pages, on what will not trigger `authentication require` event?

### ISSUE THREAD

**Issue by alexsobolenko** [scheb/two-factor-bundle#213]
Can I specify several pages, on what will not trigger `scheb_two_factor.authentication.require` event? I did not find solution for it in documentation

**Comment by scheb** [comment]
Use `access_control` in the security configuration. Paths accessible to `IS_AUTHENTICATED_ANONYMOUSLY` can be accessed even during two-factor authentication.

**Comment by alexsobolenko** [comment]
Your decision did not help me. Here is a part of my file `sqcurity.yaml`:
```yaml
    access_control:
        - { path: ^/tokensale, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
```
Here is a part of log:
```bash
[Tue May 21 21:12:55 2019] 127.0.0.1:24009 [200]: /_wdt/e2ff05
[Tue May 21 21:13:02 2019] 127.0.0.1:24013 [302]: /tokensale
[Tue May 21 21:13:03 2019] 127.0.0.1:24015 [200]: /2fa
[Tue May 21 21:13:03 2019] 127.0.0.1:24017 [200]: /build/main.22c3e5bb.css
[Tue May 21 21:13:03 2019] 127.0.0.1:24018 [200]: /build/main.7cf12fed.js
```
When I click to 'Token sale' link always redirects to `/2fa`

**Comment by scheb** [comment]
Which versions (Symfony + bundle) are you using?

Would you please provide all our your security.yaml config and the scheb_two_factor.yaml config?

**Comment by alexsobolenko** [comment]
No, I can't to provide all of this files unfortunately. We use symfony version 4.1.4 and bundle version 4.1

**Comment by scheb** [comment]
Well, that's unfortunate. Hard for me to judge if everything is configured correctly.

Is this all of your `access_control` configuration, or is there more rules?
```
    access_control:
        - { path: ^/tokensale, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
```

**Comment by alexsobolenko** [comment]
I was forbidden to show the full code here, so as not to break a trade secret.

Yes `access_control` have more rules after this. I added rule for `/tokensale` to the beginning.

**Comment by scheb** [comment]
Please keep in mind that `access_control` rules are matched in that order. If there's a path pattern matching before it reaches the rule for `^/tokensale` and that rule requires the user to be authenticated, the system will redirect to the 2fa form.

Ideally, you put the `IS_AUTHENTICATED_ANONYMOUSLY` rules first and then all the other rules.

**Comment by alexsobolenko** [comment]
Sure. Such rules are in the beginning of `access_control`.

**Comment by scheb** [comment]
Closed due to inactivity. If this is still an issue and you have new information, feel free to re-open.
