### ISSUE TITLE
always_authenticate_before_granting:true causes endless 2fa loop

### ISSUE THREAD

**Issue by scheb** [scheb/two-factor-bundle#216]
**Bundle version**: 3.x and 4.x
**Symfony version**: Any

**Description**

> Alrighty I think I tracked down in my case what is doing it, I don't think it is related to this ticket but let me know.
>
> If you have ` always_authenticate_before_granting: true` so that the roles are refreshed each page load, this causes the regular two factor provider to kick in each time, which then reverts you back to the to the two factor login.  
>
> I made a test case here: https://github.com/daum/example-twofactor-issue If you clone, set your two factor up, login, do the two factor, it will take you to /.  Refresh the page and you'll notice you are then redirected back to the 2fa page.  
>
> I'm not sure of the best solution here, after catching it it seems pretty obvious if you require an authenticate each time before checking for grants that it will trigger the regular 2fa steps.  I think maybe just adding this to the documentation as a known gotcha?

_Originally posted by @daum in https://github.com/scheb/two-factor-bundle/issues/206#issuecomment-505509154_

**To Reproduce**

1) Enable:
```yaml
security:
    always_authenticate_before_granting: true
```

2) Execute authentication and complete 2fa.
3) You're not authenticated and redirected to do 2fa from the beginning.

**Comment by scheb** [comment]
Can confirm this issue when `always_authenticate_before_granting: true` is enabled. As long as `TwoFactorToken` is present, this is not an issue.

As soon as a different token is present (after successful 2fa), the `\Symfony\Component\Security\Core\Authorization\AuthorizationChecker` is re-authenticating the token by calling the token's authentication provider.

All authentication providers are decorated with `\Scheb\TwoFactorBundle\Security\Authentication\Provider\AuthenticationProviderDecorator` to wrap the authenticated token away immediately after login. But the decorator cannot distinguish between "new login" and "re-authentication", so the token is also wrapped away in the re-authentication case and the whole process starts from the beginning.

Currently there is no way to work around this issue. Only option is to not use the `always_authenticate_before_granting: true` option.

**Comment by scheb** [comment]
v3.19.1 / v4.2.1 with the bugfix

/cc @daum

**Comment by daum** [comment]
Wow awesome job thanks!
