### ISSUE TITLE
Expose `check_path` from the `TwoFactorFirewallConfig`

### ISSUE THREAD

**Issue by zerkms** [scheb/two-factor-bundle#217]
I'm implementing captcha (conditional) to the 2FA process, and it would be another listener that jumps in right before `TwoFactorListener`.

To determine whether or not I need to validate captcha code I need the value of the `check_path` (to compare it with the current route). Yet at the moment `TwoFactorFirewallConfig` does not expose it.

Exposing it as a method, or just a generic `getOption(string $key)` would do.

Thoughts?

Thanks :-)

**Comment by scheb** [comment]
Sounds legit, but I'd prefer specific methods for the pieces of information to be exposed, rather than a generic `getOption(string $key)` method.

**Comment by scheb** [comment]
Released as v4.2.0

**Comment by zerkms** [comment]
Awesome, now I can remove reflection and reading private fields :-D

**Comment by scheb** [comment]
Well, in that case I'm especially glad we solved that for you ;)
