### ISSUE TITLE
Validation code re-generated and sent each time you try to go on another location will validating 2FA

### ISSUE THREAD

**Issue by soullivaneuh** [scheb/two-factor-bundle#223]
**Bundle version**: 4.x
**Symfony version**: 4.x

**Description**

Related to #212, but a separate issue worth it IMO.

The 2FA provider are always called when you are redirected to the 2FA page, even if the code is already sent.

**To Reproduce**

1. Login on the page, you will be redirected to the 2FA form and the email will be sent.
2. Try to go on a page that requires a full authentication
3. You are again redirected, but a new code is sent.

**Additional Context**  

See https://github.com/scheb/two-factor-bundle/issues/212#issuecomment-507314291

**Comment by scheb** [comment]
New release 4.7.0 fixes this issue.
