### ISSUE TITLE
Symfony 4.3 deprications

### ISSUE THREAD

**Issue by spacecodeit** [scheb/two-factor-bundle#225]
**Bundle version**: 4.1
**Symfony version**: 4.3.2

**Description**

- [ ] The "Scheb\TwoFactorBundle\Security\Http\Firewall\TwoFactorListener" class implements "Symfony\Component\Security\Http\Firewall\ListenerInterface" that is deprecated since Symfony 4.3, turn listeners into callables instead.
- [ ] Order of EventDispatcher::dispatch arguments

**Comment by scheb** [comment]
The callable approach is only supported from Symfony 4.3 on, but right now the bundle supports 3.4 and 4.x versions. So I cannot refactor out the depenency on `ListenerInterface` without dropping support for everything < 4.3. This is only possible with a major release, which will not happen before 5.0 actually becomes a thing.

For the transition I can already add an `__invoke` method, but it will not be working on 5.0 because the dependency on `ListenerInterface` (which will be gone in 5.0) has to be there for older versions.

**Comment by lordjancso** [comment]
Hello!

Bundle version: 4.3.1
Symfony version: 4.3.2

The interface is broken in "Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorToken".
Missing methods: getRoleNames, __serialize, __unserialize

**Comment by scheb** [comment]
I don't see these methods being part of [TokenInterface in 4.3](https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/Security/Core/Authentication/Token/TokenInterface.php). But:

```
 * @method array    __serialize()                                                                             Returns all the necessary state of the object for serialization purposes - not implementing it is deprecated since Symfony 4.3
 * @method void     __unserialize(array $data) Restores the object state from an array given by __serialize() - not implementing it is deprecated since Symfony 4.3
 * @method string[] getRoleNames()                                                                            The associated roles - not implementing it is deprecated since Symfony 4.3
```

So not implementing these is a deprecation, but cannot say it's "broken".

**Comment by lordjancso** [comment]
If you have a [custom voter](https://symfony.com/doc/current/security/voters.html#creating-the-custom-voter) it goes through the [security listener](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/EventListener/SecurityListener.php#L91) which depends on the `getRoleNames` method.

**Comment by scheb** [comment]
Far from ideal to depend on a method, that's not part of the interface.

We'll I can add these new methods to make it compatible with 4.3+ versions. Shouldn't make a difference for the other Symfony versions supported by the bundle.

**Comment by lordjancso** [comment]
Yeah, that would be nice to add these methods in the current version for more compatibility. Something like this:

```
    public function getRoles()
    {
        return $this->authenticatedToken->getRoles();
    }

    public function getRoleNames()
    {
        return $this->authenticatedToken->getRoleNames();
    }

    public function __serialize()
    {
        return [$this->authenticatedToken, $this->credentials, $this->providerKey, $this->attributes, $this->twoFactorProviders];
    }

    public function serialize()
    {
        return serialize($this->__serialize());
    }

    public function __unserialize(array $data)
    {
        [$this->authenticatedToken, $this->credentials, $this->providerKey, $this->attributes, $this->twoFactorProviders] = $data;
    }

    public function unserialize($serialized)
    {
        $this->__unserialize(\is_array($serialized) ? $serialized : unserialize($serialized));
    }
```

**Comment by scheb** [comment]
Serialization is hard. Finally found an implementation that's compatible with all supported Symfony versions.

**Comment by scheb** [comment]
Release v4.4.0 &  v3.21.0 with these changes.

**Comment by maxhelias** [comment]
I think closing the ticket is not done on purpose because it is still missing a step.
I would try to fix it soon. Maybe I have a solution, I need to try it before

**Comment by scheb** [comment]
@maxhelias Correct, we still have the issue with the ListenerInterface. The changes have only been introduced with Symfony 4.3, so imo there is no backwards compatible solution that avoids the deprecation AND is compatible with all Symfony versions supported by the bundle. But if you have a solution for this I'd be all up for it :)
