### ISSUE TITLE
Provide autowiring for EmailTwoFactorProvider

### ISSUE THREAD

**Issue by soullivaneuh** [scheb/two-factor-bundle#228]
It can be sometime used directly to re-generate and send a code from the back-office, as an example.

**Comment by scheb** [comment]
Want to send me a PR?

**Comment by scheb** [comment]
After checking it: Wouldn't make it more sense to use the `Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Email\Generator\CodeGenerator`, respectively `Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Email\Generator\CodeGeneratorInterface`? The provider is actually the class that integrates with the two-factor authentication mechanism. To me, that doesn't seem to be the right tool to generate and send the code. The CodeGenerator would be the more appropriate one.

**Comment by soullivaneuh** [comment]
I used `EmailTwoFactorProvider` to be sure to reproduce manually the 2FA starting process. If something change in the process, I will not have to update anything.

But yes, I may use `CodeGeneratorInterface`.

**Comment by scheb** [comment]
To wrap-up this issue. Auto-wiring for CodeGeneratorInterface is there in v3.22.0 and v4.5.0.
