### ISSUE TITLE
Docker deployment - trustedCookie issue

### ISSUE THREAD

**Issue by LucasSouriau** [scheb/two-factor-bundle#229]
**Bundle version**: 3.19.0
**Symfony version**: 4.2.8

Hey mate!

Thanks for last time, you helped me a lot with the #211 issue. Hope the fix for the v4 will be push soon.

Anyway, got a new issue, maybe it ain't link to your bundle but I better ask. The thing is that we're working in continuous deployment with our application. Each time we're merging dev branch in prod, docker and all the set up are re-init and we load again the saved database. 

But there's a problem with people using 2FA and they've set their browser as a trusted device. The cookie is still valid and you can see it in the browser dev tools. But the 2fa form shows up after login and send a code again after a new deployment has been done..

If you have any ideas with this?

**Comment by scheb** [comment]
I cannot see an obvious issue.

I'd recommend to debug what's happening in [TrustedDeviceManager](https://github.com/scheb/two-factor-bundle/blob/master/Security/TwoFactor/Trusted/TrustedDeviceManager.php) and further down the execution path. That's the class responsible for making the decision whether your trusted cookie is valid or not (and therefore if it asks for two-factor authentication).

**Comment by LucasSouriau** [comment]
Hey! So I've find out what the problem was. The Symfony application secret was randomly generated during the git deployment. That's why I had no ways to see it local. Just had to make it static to get the thing work.
Thanks man, you can close the issue btw ;)
