### ISSUE TITLE
Logout not working with Symfony Profiler activated

### ISSUE THREAD

**Issue by robbah** [scheb/two-factor-bundle#234]
**Bundle version**: 4.5.0
**Symfony version**: 3.4.30

**Description**
While running the profiler in the background (app_dev.php), i cannot use the logout button. It redirects me back to the 2fa login form.
When i remove the app_dev.php from the url, the logout works fine.

**To Reproduce**
1. Go to 'http://my-dev-project.local/app_dev.php/logout'
2. The user isn't logged out.
3. Go to 'http://my-dev-project.local/logout'
4. User is logged out.

**Additional Context**  
It seems to go wrong in the TwoFactorAccessDecider isAccessible() function

**Comment by scheb** [comment]
1) Please post your security.yaml configuration.

2) Could you please check what's returned here?
https://github.com/scheb/two-factor-bundle/blob/6e23a3f7478d29d599dbb5e7fa0551d2130d688f/Security/Authorization/TwoFactorAccessDecider.php#L57

**Comment by robbah** [comment]
1) This is the firewall and access_control part:
`    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            anonymous:  ~
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check
            form_login:
                login_path:  login
                check_path:  login_check
                default_target_path: dashboard_homepage
                # csrf token options
                csrf_token_generator: security.csrf.token_manager
                csrf_parameter: _token
            logout:
                path:   /logout
                target: /
                
    access_control:
        - { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS, requires_channel: https }
        - { path: ^/, roles: ROLE_MNGR, requires_channel: https }`

2) '/app_dev.php/logout'

**Comment by scheb** [comment]
`- { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }`
This one requires https, while your logout URL is _not_ https but http. Therefore the rule doesn't match. Remove either the `requires_channel` or make your logout route https, then it will work.

Normally this part should handle the logout path:
https://github.com/scheb/two-factor-bundle/blob/6e23a3f7478d29d599dbb5e7fa0551d2130d688f/Security/Authorization/TwoFactorAccessDecider.php#L57-L60
but the prefixed `app_dev.php` somehow breaks the path matching. Would need to investigate if there's a way to improve that.

**Comment by robbah** [comment]
My logout URL is https. I accidentally entered http instead of https in my logout URL at the top of this issue..
So my logout URL is: 'https://my-dev-project.local/app_dev.php/logout'

**Comment by scheb** [comment]
Well, but then the `access_control` rule should actually let your logout route pass. I don't know why this is not happening. I'd recommend you dig further down this code path:

https://github.com/scheb/two-factor-bundle/blob/6e23a3f7478d29d599dbb5e7fa0551d2130d688f/Security/Authorization/TwoFactorAccessDecider.php#L51-L54

For some reason either the `accessMap` doesn't match the logout path to a firewall or the `accessDecisionManager` doesn't allow access to the path.

**Comment by robbah** [comment]
It seems to go wrong because i have set in my security.yml:
```
    access_decision_manager:
        # strategy can be: affirmative, unanimous or consensus
        # set to unanimous: if one voter denies access, access is denied!
        strategy: unanimous
```

This voter gives me access denied which is why i am being redirected back to the 2fa login form:
```
object(Symfony\Component\Security\Core\Authorization\Voter\AuthenticatedVoter)[1275]
  private 'authenticationTrustResolver' => 
    object(Scheb\TwoFactorBundle\Security\Authentication\AuthenticationTrustResolver)[313]
      private 'decoratedTrustResolver' => 
        object(Symfony\Component\Security\Core\Authentication\AuthenticationTrustResolver)[311]
          private 'anonymousClass' => string 'Symfony\Component\Security\Core\Authentication\Token\AnonymousToken' (length=67)
          private 'rememberMeClass' => string 'Symfony\Component\Security\Core\Authentication\Token\RememberMeToken' (length=68)
```

**Comment by scheb** [comment]
Latest releases 4.6.0 and 3.23.0 solve this issue.
