### ISSUE TITLE
Compile Error: Declaration of App\Entity\User::getTotpAuthenticationConfiguration()

### ISSUE THREAD

**Issue by JSmythSSG** [scheb/two-factor-bundle#237]
When adding the interface as below I get the a compile error:

`class User implements UserInterface, TwoFactorInterface`

`Compile Error: Declaration of App\Entity\User::getTotpAuthenticationConfiguration(): App\Entity\TotpConfigurationInterface must be compatible with Scheb\TwoFactorBundle\Model\Totp\TwoFactorInterface::getTotpAuthenticationConfiguration(): ?Scheb\TwoFactorBundle\Model\Totp\TotpConfigurationInterface
`

I've added the following to my user entity

 ```
    /**
     * @ORM\Column(name="totp_secret", type="string", nullable=true)
     */
    private $totpSecret;

  public function isTotpAuthenticatorEnabled(): bool
    {
        return $this->totpSecret ? true : false;
    }

    public function getTotpAuthenticationUsername(): string
    {
        return $this->username;
    }

    public function getTotpAuthenticationConfiguration(): TotpConfigurationInterface
    {
        // You could persist the other configuration options in the user entity to make it individual per user.
        return new TotpConfiguration($this->totpSecret, TotpConfiguration::ALGORITHM_SHA1, 20, 8);
    }
```

Any help would be much appreciated

**Comment by scheb** [comment]
The method signature has to match the signature from the interface. You're missing the `use` statement for `Scheb\TwoFactorBundle\Model\Totp\TotpConfigurationInterface` in your file.

**Comment by JSmythSSG** [comment]
This is what I have at the top of my User entity 

`<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Scheb\TwoFactorBundle\Model\Totp\TotpConfiguration;
use Scheb\TwoFactorBundle\Model\Totp\TwoFactorInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, TwoFactorInterface`

**Comment by JSmythSSG** [comment]
Ah yeh sorry! that wasnt listed on the guide was it? Because I copied the it from there

**Comment by JSmythSSG** [comment]
Thats now working! thank you one step closer.
Just need to work out why its saying code_invalid now when I try to use a generated code
