### ISSUE TITLE
IS_AUTHENTICATED_2FA_IN_PROGRESS is not being assigned

### ISSUE THREAD

**Issue by maikelreyes** [scheb/two-factor-bundle#239]
Hi there, I'm using the google authenticator provider, but every time that I login, when the page redirects to the /2fa url, there no active roles at all, and for this reason the client is returned to the login page.

Debugging the code at the TwoFactorInProgressVoter class, I detect that:
```
if (self::IS_AUTHENTICATED_2FA_IN_PROGRESS === $attribute) {
     return VoterInterface::ACCESS_GRANTED;
}
if (AuthenticatedVoter::IS_AUTHENTICATED_ANONYMOUSLY === $attribute) {
     return VoterInterface::ACCESS_GRANTED;
}
```

never fic the criteria, because the attibutes array at this stage only contains "ROLE_ADMIN".

MAy I forgot something to do once the user is logged ? Can you provide some ideas?

**Comment by maikelreyes** [comment]
security,yaml sample...
providers:
        ...
        cms_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        backoffice:
            pattern: ^/(admin|dtc_queue|dtc_grid|command-scheduler)
            anonymous: ~
            provider: cms_user_provider
            logout:
                path:   cms_logout
                target: cms_login
            guard:
                authenticators:
                    - App\Security\AdminFormAuthenticator
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check
                default_target_path: /admin
                provider: cms_user_provider
        ...
    access_control:
         - { path: ^/(admin/login|managers/login|reset_password|managers/reset_password), roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }

**Comment by scheb** [comment]
In the voter class, `$attributes` contains the roles that are required to get access, not that are present. If you see `ROLE_ADMIN` in that array, it means the system believes you must have `ROLE_ADMIN` to access that route.

Is that all your `access_control` configuration or did you shorten it? Please provide the complete config.

Did you see the troubleshooting guide in the docs? I think [this case](https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/troubleshooting.md#two-factor-authentication-form-is-not-shown-after-login) is closest to the issue you're facing.

**Comment by maikelreyes** [comment]
attached the full security.yaml file
[config.zip](https://github.com/scheb/two-factor-bundle/files/3665586/config.zip)

[AdminFormAuthenticator.zip](https://github.com/scheb/two-factor-bundle/files/3665587/AdminFormAuthenticator.zip)

**Comment by scheb** [comment]
You have to rearrange your `access_control` rules. They are executed in that order and the first matching rule wins, therefore
`- { path: ^/admin, roles: ROLE_ADMIN  }`
matches before
`- { path: ^/admin/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }`

It has to be the other way round. In general it makes sense for `access_control` to have more specific rules come first and the more open ones (matching entire sub-paths) later.

**Comment by maikelreyes** [comment]
Thanks a lot, now it works!
