### ISSUE TITLE
U2F Support

### ISSUE THREAD

**Issue by Uneo7** [scheb/two-factor-bundle#240]
Support for U2F Hardware keys could be a good addition to this bundle.

The key register/login process would be similar to the actual Google Auth but it would ask for the key to be pressed instead of the usual 6 digit code.

**Note :** Allowing multiple keys is a must have for hardware keys.

The new protocol WebAuthn could also be a good solution instead of Fido U2F but I'ts an absolute mess atm (I can't find any open source implmentation working correctly).

**U2F for starters :** 

Fido U2F is a protocol which allow the user to use a hardware usb key as a authentication method. When asked for the user press a little button on the key to validate the login.

**Comment by scheb** [comment]
Please have a look at [darookee/u2f-two-factor-bundle](https://github.com/darookee/u2f-two-factor-bundle), is that what you're looking for?

**Comment by Uneo7** [comment]
It seems so thx. Do you know if I can stilll use the classic Google auth instead if I want to ? (I want to give my users the choice)

**Comment by scheb** [comment]
Yes, you can support multiple 2fa methods and let the user choose the one(s) they want to use.

**Comment by Uneo7** [comment]
Okay thx for you quick reply.
Have a good day.
