### ISSUE TITLE
Problem of creating side-wide firewall with 2fa authentication

### ISSUE THREAD

**Issue by PWalkow** [scheb/two-factor-bundle#251]
**Bundle version**: 4.8.0
**Symfony version**: 3.428

**Description**
I've got a problem to set up the 2fa authentication with example where all user needs to be authenticated on all pages with multiple custom guard authenticators:

```#security.yaml
firewalls:
   main:
      two _factor: 
         auth_form_path: /2fa
         check_path: /2fa_check

    guard:
         authenticators: 
                 - '@custom_authenticator_1'
                 - '@custom_authenticator_2'
         entry_point: '@custom_entry_point'

access_control:
     - { path: ^/2fa_login, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
     - { path: ^/2fa_check, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
     - { path: ^/, role: IS_AUTHENTICATED_FULLY }
```

So far I've managed to be redirected to login properly, authenticator is giving `PostGuardAuthenticationToken` after stardard login, I'm landing on /2fa with `TwoFactorToken`, submitted passing code to custom 2fa authenticator that return true on `checkCode` and seeing 
``` security | User has been two-factor authenticated successfully.      ``` in logs
while receiving a successful redirect to '/' page.
... and when landing back on homepage, `GuardAuthenticationProvider` throws `AuthenticationExpiredException` as token in there is `PostAuthenticationGuardToken` already and not `PreAuthenticationGuardToken` as implementation requires.

How to set up the custom authenticators / access_control paths and possible other places to make 2fa work with page-wide security?

**Comment by scheb** [comment]
Does your user entity implement `AdvancedUserInterface`?

**Comment by PWalkow** [comment]
No, it is just simple UserInterface

**Comment by scheb** [comment]
> ... as token in there is `PostAuthenticationGuardToken` already and not `PreAuthenticationGuardToken` as implementation requires.

Actually that's how it's supposed to be. The question is, why you're ending up in `GuardAuthenticationProvider`, that's the thing that should not even happen.

I have the suspicion that `isAuthenticated` on your token is no longer `true` when 2fa has been completed. This typically happens when you have a custom serialize/unserialize implementation for the user entity, but it does not serialize all the attributes that are necessary to check the validity of the user. Things like an "is account active" true/false flag or alike.

Could you please post the implementation of your user entity?

**Comment by scheb** [comment]
@PWalkow Have you been able to solve the problem?

**Comment by PWalkow** [comment]
I couldn't reproduce the issue on symfony v4.4, I guess the order of security events might have changed. As I was trying to make it work on symfony v3.4 without a success - now I'm during the process of upgrading, unfortunately I had no time to investigate v3.4 but exactly same example works for higher symfony version.

**Comment by scheb** [comment]
Then I'm closing this issue. Feel free to reopen when the problem reappears.
