### ISSUE TITLE
What is the replacement for Scheb\TwoFactorBundle\Security\TwoFactor\Session\SessionFlagManager for sy

### ISSUE THREAD

**Issue by kishorejabu** [scheb/two-factor-bundle#256]
Unable to find the Scheb\TwoFactorBundle\Security\TwoFactor\Session\SessionFlagManager for a newer version and as well as no document available about the replacement or in UPGRADE file.
could you please help

**Comment by scheb** [comment]
What are you doing with it? It's meant to be an internal service that shouldn't be used directly.

**Comment by kishorejabu** [comment]
Thank you for the response @scheb . We will check and get back to you if we need any help.
