### ISSUE TITLE
Restrict 2FA trusted device cookie to path

### ISSUE THREAD

**Issue by Toflar** [scheb/two-factor-bundle#261]
Right now the `TrustedCookieResponseListener` sets a cookie which has no path restriction (so it's configured to `/`).
This will cause issues with caching because there are many reverse proxies that disable caching when cookies are present as they might identify a user for the app (which the 2FA trusted device cookie indeed does).

So let's imagine everything user related for me is at `/admin`, we could restrict that cookie to this path so everything else on that website can perfectly be served from a shared reverse proxy cache.
Actually we know the `check_path` don't we? We could restrict it to that path because for all the other cases, that cookie never needs to be sent to the server, does it?

**Comment by scheb** [comment]
Currently the path is hard-coded in https://github.com/scheb/two-factor-bundle/blob/master/Security/TwoFactor/Trusted/TrustedCookieResponseListener.php#L81

I'd suggest to make this a config option. Thoughts?

**Comment by Toflar** [comment]
Yes I know. The cookie is only ever used on the check path, isn‘t it? Then imho that should be the config value.

**Comment by scheb** [comment]
> The cookie is only ever used on the check path, isn‘t it?
Yes, I think so.

But still, I'd solve it with a config option, because you never know what people do in their applications. If I'd automatically set it to the check path, then the next person comes and has a use-case why it shouldn't be under the check path. The configuration option would give everyone the flexibility they need.

**Comment by Toflar** [comment]
Agreed. It could default to `check_path` though :)

**Comment by scheb** [comment]
Default will be `/`, because I want to it to be backward compatible.

**Comment by scheb** [comment]
New configuration option available in 3.27.0 / 4.12.0

**Comment by Toflar** [comment]
Agreed! Thanks a lot!!
