### ISSUE TITLE
Using multiple authentication methods in paralell

### ISSUE THREAD

**Issue by gala132** [scheb/two-factor-bundle#28]
Hi!
I would like to use multiple authentication methods at once.
I mean, for example i wan't to be able to use googleauth and email auth at once.
So if i chose to not use google authentication i shall be able to use email authentication instead.
The UI part is simple to me, but how can i achieve that thus with only one requestlistener.

**Comment by scheb** [comment]
Don't worry about the request listener. You simply enable both authentication methods in the bundle configuration. Then implement both `Scheb\TwoFactorBundle\Model\Email\TwoFactorInterface` and `Scheb\TwoFactorBundle\Model\Google\TwoFactorInterface` in your user entity.

The interfaces provide you with a method that is used to determine, if the authentication method is supported for that user. Take a look at the source code of those interfaces:

Scheb\TwoFactorBundle\Model\Email\TwoFactorInterface:
```php
    /**
     * Return true if the user should do two-factor authentication
     *
     * @return boolean
     */
    public function isEmailAuthEnabled();
```

Scheb\TwoFactorBundle\Model\Google\TwoFactorInterface:
```php
    /**
     * Return the Google Authenticator code
     * When an empty string or null is returned, the Google authentication is disabled.
     *
     * @return string|null
     */
    public function getGoogleAuthenticatorSecret();
```

You could even have both authentication methods enabled for a user at the same time. Then you'll get something like a "three-factor authentication", first asking for the Google Authenticator code, and when that one was accepted, also asking for the email authentication code. Might be a total overkill, but it works.

**Comment by gala132** [comment]
Yeah, but if i would like to make it like this:
A simple form, if the google authenticator is picked and code sent then the authenticator will validate that if someone picks for example email, then the email code will be validated. So i probably stated the name of the issue badly will correct it.

**Comment by scheb** [comment]
If user didn't choose any authentication method in the profile settings: isEmailAuthEnabled returns false, getGoogleAuthenticatorSecret returns null => No two-factor dialog is shown.

If user has choosen email code authentication in the profile settings: isEmailAuthEnabled returns true, getGoogleAuthenticatorSecret returns null => Email two-factor dialog is shown

If user has choosen Google Authenticator in the profile settings: isEmailAuthEnabled returns false, getGoogleAuthenticatorSecret returns the secret => Google Authenticator two-factor dialog is shown

Forcing the user to choose only ONE two-factor method is just a matter of implementation. Or do I get something wrong.

**Comment by gala132** [comment]
It is like you say.
But let's assume this one, xy forgot his phone somewhere where he had the Google Authenticator and his secret saved, then the user could chose the email method instead (since he has an email set) so we could send the code there and let the user authenticate with that one instead of the google authenticator.

**Comment by scheb** [comment]
Unfortunately the design of the bundle doesn't allow you to choose the two-factor authentication method on every login. That's also a matter of security, because if someone wants to hack your account and they already have access to your email inbox, they can just switch to the weaker email authentication and the Google Authenticator that you're using to protect the account becomes useless.

For the case that you need to login and you don't have access to the two-factor device (mobile or email inbox), the bundle has the concept of [backup codes](https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/backup_codes.md).

**Comment by gala132** [comment]
Hi!
Thanks, you have a valid point, will rethink this.
