### ISSUE TITLE
Bypass 2fa for specific user

### ISSUE THREAD

**Issue by doblum** [scheb/two-factor-bundle#280]
Is it possible to bypass the 2fa for specific users ? 
Maybe with a attribute set on the user.
I want that the user can enable 2fa himself instead of using it always.
I’m using an Ldap Guard and fosuserbundle.

**Comment by scheb** [comment]
All the `TwoFactorInterface`s have a method `is...Enabled`, which you can use to control if that user can/should to 2fa. For example, [here's the method](https://github.com/scheb/two-factor-bundle/blob/master/Model/Email/TwoFactorInterface.php#L12) in the email authenticator, the other authentication methods have a similar method.

Does that help?

**Comment by doblum** [comment]
That works.
Thank you!
