### ISSUE TITLE
2FA and FOSOAuthServer

### ISSUE THREAD

**Issue by softrare** [scheb/two-factor-bundle#282]
Hi! My question is, have you ever implemented this with FOSOAuthServer? I have an identity provider which provides access tokens on basis of username and password, but want to implement Google Authenticator as 2FA. Really hitting a brick wall after going through your tutorial about how to implement the Google Authenticator https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/providers/google.md . My main problem is where to include the 2fa route. While yes, it is declared in the firewall, I have no idea where to set it in my application for the 2fa formular to be shown once the oauth login was completed. Sorry for this question, I am a Symfony beginner and the symfony auth system is still pretty much magic for me. Thanks for any efforts!

**Comment by scheb** [comment]
> My main problem is where to include the 2fa route. While yes, it is declared in the firewall, I have no idea where to set it in my application for the 2fa formular to be shown once the oauth login was completed.

The 2fa route is linked with the controller that is coming with the bundle, see here: https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/installation.md#step-3-define-routes

The bundle will then automatically redirect to that route when it wants the user to go through two-factor authentication.

One thing you shouldn't miss is to configure the custom token class that FOSOAuthServer is using:

```
# config/packages/scheb_two_factor.yaml
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - FOS\OAuthServerBundle\Security\Authentication\Token\OAuthToken
```

And then it should work, as long as your user entity has GoogleAuthenticator configured and activated.

**Comment by softrare** [comment]
Thank you! I had the token configuration in scheb_two_factor.yaml different, that's probably a confusing error skipped down the road. I think I know where my original problem occurred, could it be in fos_oauth_server.yaml where it says:

`
    authorize:
        form:
            type:               App\Form\AuthorizationType
            handler:            App\Form\Handler\TwoFactorAuthorizationFormHandler
            name:               fos_oauth_server_authorize_form
            validation_groups:
                # Defaults:
                - Authorize
                - Default

`

So there is where it selects a current "dummy" 2fa formular which I would now want to replace with yours. But I don't know what values to use instead, using your 2fa_login route for "name" does nothing, and removing type and handler obviously brings up an exception. Any idea what I can fill in here? Do you have a form type and handler which can be used here? Thank you very much in advance!

**Comment by scheb** [comment]
I believe this should have nothing to do with the 2fa form. The FOSOAuthServer bundle's responsibilty is to identify the user who wants to login. It doesn't need to know about 2fa at all, because the two-factor-bundle would automatically hook in after this initial authentication step and redirect to the user to the 2fa authentication form.

**Comment by softrare** [comment]
Yes, I understand. By that logic I would have to remove that whole "authorize" paragraph from fos_oauth_server.yaml but then I get this https://ibb.co/8cFy3yS So it's waiting for the authcode in the template, I just don't know where to supply my user entity class where I implemented your TwoFactorInterface. It's probably something very small missing.

**Comment by scheb** [comment]
Err, I'm not sure what's happening there. I have to say I have no experience with FOSOAuthServer bundle, so I'm trying to understand what you're doing.

This `form. authCode` field, is that part of the FOSOAuthServer bundle? Or is that a field that you just added there for the user to enter the 2fa code?

**Comment by softrare** [comment]
This formular/template where the error occurs seems to be part of the FOSOAuthServer bundle, indeed.

**Comment by scheb** [comment]
Yes, I've understood this, that this form is part of the bundle. But it didn't answer my question regarding this `form.authCode` field. So once again:

This `form.authCode` field, is that part (I mean: part of the feature set) of the FOSOAuthServer bundle? Or is that a field that you just added there for the user to enter the 2fa code?

**Comment by softrare** [comment]
I have not added anything, but it seems the "dummy" 2FA handler which I am trying to replace somehow provides it the way FOSOAuthServer bundle expects.. I also do not understand why it asks for it, very weird. Is it something in my security.yaml? I added the lines you suggested in your tutorial to the main firewall:

> firewalls:
>         oauth_token:
>             pattern:    ^/oauth/v2/token
>             security:   false
> 
>         oauth_authorize:
>             pattern:    ^/oauth/v2/auth
>             context: custom_security_context
>             access_denied_handler: App\Security\AccessDeniedHandler
>             form_login:
>                 provider: fos_userbundle
>                 csrf_token_generator: security.csrf.token_manager
>                 check_path: oauth_server_auth_login_check
>                 login_path: oauth_server_auth_login
>                 default_target_path: /profile
>                 target_path_parameter: redirect_uri
>             anonymous: true	
> 			
>         main:
>             pattern: ^/
>             anonymous: true
>             context: custom_security_context
>             form_login:
>                 provider: fos_userbundle
>                 csrf_token_generator: security.csrf.token_manager
>                 default_target_path: /profile
>             logout:
>                 target: /login
>             two_factor:
>                 auth_form_path: 2fa_login    # The route name you have used in the routes.yaml
>                 check_path: 2fa_login_check  # The route name you have used in the routes.yaml		
> 				
>     access_control:
>         - { path: ^/oauth/v2/auth, role: IS_AUTHENTICATED_ANONYMOUSLY }
>         - { path: ^/api/.+, roles: [ IS_AUTHENTICATED_FULLY ] }
>         # This makes the logout route available during two-factor authentication, allows the user to cancel
>         - { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
>         # This ensures that the form can only be accessed when two-factor authentication is in progress
>         - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }

and of course the routes are there in routes.yaml

> fos_user:
>     resource: "@FOSUserBundle/Resources/config/routing/all.xml"
> 
> fos_user_security:
>     resource: "@FOSUserBundle/Resources/config/routing/security.xml"
> 
> fos_user_security_login:
>     path: "/login"
>     controller: App\Controller\SecurityController::loginAction
> 
> oauth_server_auth_login:
>     path: "/oauth/v2/auth/login"
>     controller: App\Controller\SecurityController::loginAction
> 
> oauth_server_auth_login_check:
>     path: "/oauth/v2/auth/check"
>     controller: App\Controller\SecurityController::checkAction
> 
> 2fa_login:
>     path: /2fa
>     defaults:
>         _controller: "scheb_two_factor.form_controller:form"
> 
> 2fa_login_check:
>     path: /2fa_check

Seems to me right now that FOSOAuthServer is more barebones than one would expect and that it needs some extra coding. Or can you see something obviously wrong in these config files? Again, thank you so much for your help, it's very overwhelming especially as starter with Symfony.

**Comment by scheb** [comment]
Oke, honestly, that's way to much. I'd need to read up how FOSOAuthServerBundle works and make a lot of guesses how your app works. I'm not going to do that, sorry. There must be something wrong with how your app is set-up, but I don't really get it.

Since you've just started with Symfony, my suggestion would be forget all this OAuth stuff for now and make your authentication system work with a basic username/password form. As soon as this is working you may want to add a OAuth as an alternative authentication method or try to add 2fa at this stage. But don't try to do all of it at once, make it work step by step.

What you have to understand is, two-factor authentication the way the bundle implements it, is a 2-step process. First, you authenticate as normal to identify yourself as "user X". It doesn't matter how you identify yourself, if that's via username/password or via OAuth. After the user has authenticated, and only then, the two-factor-bundle will become active and eventually redirect to the user to the two-factor authentication form (under the condition that 2fa is active for that user, which is controlled by the TwoFactorInterface you have to implement in the user entity). And only when that second step is completed successfully, the system will grant them access. So it doesn't just happen all of it in a single step.

I have this little test application that I'm using for myself to test two-factor authentication, maybe that helps you to get a better idea how it's working: https://github.com/scheb/two-factor-app

**Comment by softrare** [comment]
Yes, thank you so much for your efforts!

**Comment by softrare** [comment]
The issue was on my side, the FOSOAuthServer template was overridden locally and that's why it didn't work, but we solved now in a different way with the sonata package. Still I wanted to say thank you for your quick help!
