### ISSUE TITLE
Additional "@" appearing after username when server_name not provided.

### ISSUE THREAD

**Issue by AaronCritchley** [scheb/two-factor-bundle#29]
My site uses email as the username, this means that what should display as "user@emailprovider.com" turns into "user@emailprovider.com@" when server_name is left blank (or the line is commented out).

Is there a flag I'm missing or should the "@" be removed when server_name is not passed or null?

I can give the implementation a shot if the issue is not just me missing a flag or misunderstanding the config.

**Comment by AaronCritchley** [comment]
I've solved this issue in the pull request linked above, let me know if there's anything else.

**Comment by scheb** [comment]
Fixed with 1.4.7 release
