### ISSUE TITLE
LogoutHandlerInterface is deprecated since Symfony 5.1

### ISSUE THREAD

**Issue by thomas2411** [scheb/two-factor-bundle#290]
**Bundle version**: 3.29.0
**Symfony version**: 5.1.0

**Description**
`User Deprecated: The "Scheb\TwoFactorBundle\Security\Authentication\RememberMe\RememberMeServicesDecorator" class implements "Symfony\Component\Security\Http\Logout\LogoutHandlerInterface" that is deprecated since Symfony 5.1.`

**Comment by scheb** [comment]
Yes, I know. For the matter of keeping backwards compatibility with older Symfony versions this will not go away until Symfony 6 is released and the interface is completely going away. It's a deprecation notice in the end, so nothing to worry about.

**Comment by scheb** [comment]
Closing this, as we won't be able to change this any soon.

**Comment by fmonts** [comment]
To fix the deprecation we have to upgrade to scheb/2fa? Is there a migration guide/any BC changes? 
EDIT: found [here](https://github.com/scheb/2fa/blob/5.x/UPGRADE.md) :)

**Comment by scheb** [comment]
There is currently no bundle version to make this deprecation message go away. The interface is necessary for backwards compatibility with Symfony versions before 5.1. In the end it's a deprecation message, nothing seriously to worry about. When Symfony 6 approaches (which will be the version removing the interface) there will be a solution for this issue.

**Comment by fmonts** [comment]
ok, it's a little annoying to see this notice every time I run phpunit, hope it will be fixed sooner or later... If I have time I'll try to fork and make a pull request

**Comment by scheb** [comment]
A PR would by very welcomed :) Please issue it against `scheb/2fa` as this version (4.x) doesn't receive feature updates anymore.
