### ISSUE TITLE
FatalThrowableError in RememberMeServicesDecoratorCompilerPass

### ISSUE THREAD

**Issue by enemis** [scheb/two-factor-bundle#300]
**Bundle version**: 4.18.2
**Symfony version**: 3.4.35
**PHP**: 7.4

**Description**
if you are using php 7.4 the symfony will crush with FatalThrowableError "Type error: substr() expects parameter 1 to be string, int given" in RememberMeServicesDecoratorCompilerPass.php line 29
This happens because in some cases $definitionId might be an integer instead of a string.

` // Find all remember-me listener definitions
        $prefixLength = \strlen(self::REMEMBER_ME_LISTENER_ID_PREFIX);
        foreach ($container->getDefinitions() as $definitionId => $definition) {
            if (self::REMEMBER_ME_LISTENER_ID_PREFIX === substr($definitionId, 0, $prefixLength)) {
                $this->decorateRememberMeServices($container, $definition);
            }
        }`

**Comment by scheb** [comment]
How comes that `$definitionId` is an integer? Shouldn't that be the id (string) of the service definition? I'd like to understand the use-case.

**Comment by enemis** [comment]
As i understood ServiceLocator has id 0
<img width="1344" alt="Снимок экрана 2020-09-21 в 14 44 03" src="https://user-images.githubusercontent.com/341616/93762900-15e60700-fc19-11ea-88a1-7958ac6f2d0e.png">
<img width="1344" alt="Снимок экрана 2020-09-21 в 14 47 00" src="https://user-images.githubusercontent.com/341616/93763006-52196780-fc19-11ea-9411-7c2fa09fac31.png">

**Comment by scheb** [comment]
That's odd, I've never seen that before. Well, since it's a small fix that doesn't hurt I'm going to merge the change and create a bugfix release. Thank you!

**Comment by enemis** [comment]
Awesome thanks!
