### ISSUE TITLE
Templating ServiceCircularReference

### ISSUE THREAD

**Issue by cjgordon** [scheb/two-factor-bundle#33]
Hi all,

Just wonder if anyone had seen this error before:

     Circular reference detected for service "templating", path: "nelmio_api_doc.event_listener.request -> nelmio_api_doc.formatter.html_formatter -> templating -> twig -> security.authorization_checker -> security.access.decision_manager -> scheb_two_factor.security_voter -> scheb_two_factor.provider_collection -> scheb_two_factor.security.google.provider".

If I disable either nelmio_api_doc or scheb_two_factor this error goes away but I cannot figure out how to combat the circular reference but still get the functionality of both bundles.

Symfony2: 2.7.7
Scheb Two Factor: 1.5

Previous these bundles worked fine for me, I suspect a composer update has broken things. Any pointers would be much appreciated.

Cheers
Chris

**Comment by bassrock** [comment]
I had the same issue since Two Factor upped to version 2.5. I had to keep it back at 2.4. I also use nelmio_api_doc as well.

**Comment by cjgordon** [comment]
Bingo. Thanks heaps for quick reply!

**Comment by guilhermednt** [comment]
I have the same problem, but `nelmio_api_doc` is not being mentioned for me, instead I've got this:

```
Circular reference detected for service "security.authorization_checker", path: "tos.agreement.listener -> security.context -> security.authorization_checker -> security.access.decision_manager -> scheb_two_factor.security_voter -> scheb_two_factor.provider_collection -> scheb_two_factor.security.google.provider -> templating -> twig".
```

[`tos.agreement.listener`](https://github.com/PROCERGS/tos-bundle/blob/master/EventListener/CheckAgreementListener.php) is mine. Is there something I can do besides freezing the version to 1.4?
