### ISSUE TITLE
Error if a route can handle no POST.

### ISSUE THREAD

**Issue by ickbinhier** [scheb/two-factor-bundle#36]
When I call a URL that no POST can handle I get the following message.

No route found for "POST /buchung/dsh/anmeldung/29": Method Not Allowed (Allow: GET, HEAD) 

Is there a solution?

**Comment by tubssp** [comment]
The problem occurs naturally only on when the user on a route is the no POST can.

I have now resorted me so that I have a fixed route set the POST can. But the commodity is not, of course.

**Comment by scheb** [comment]
The problem seems to be, that URL validation of the routing component is triggered before two-factor authentication. At the moment I have no idea how to fix it. I'm not deep enough into Symfony internals for that.

**Comment by tubssp** [comment]
Does the form need to be sent to the original route because? Or can I form also be geschcickt to a specially defined Fake route? White Scheb / two-factor-bundle then where I really wanted to go?

I try that tomorrow times ...

**Comment by scheb** [comment]
I was able to reproduce the problem, but unfortunately I didn't find a way to prevent the RouterListener from throwing that exception.
A solution would be to post to a route which supports POST requests. But you will lose the target URL! The bundle will always redirect (with GET) to the URL the post has been sent to.

**Comment by stof** [comment]
> The bundle will always redirect (with GET) to the URL the post has been sent to.

This seems to be the issue. Storing the needed target URL in the session (as done for form login in symfony) looks better.

**Comment by ickbinhier** [comment]
@scheb Has someone already tried?

**Comment by scheb** [comment]
No, not yet. This would require rewriting the parts of the bundle, where the authentication form is being displayed.

**Comment by scheb** [comment]
This issue is solved in the upcoming 3.0 version. Check out the beta.
