### ISSUE TITLE
Trusted IP address feature

### ISSUE THREAD

**Issue by YohannLYD** [scheb/two-factor-bundle#37]
Hi all,

I was wondering if there was a way to have a verification of the user's IP address prior to sending an authentication code which would be acting the same way as the trusted computer feature.

This idea for my application is to override the second factor if the users signs in from an identified IP (a company for example).

I am not sure if adding a custom authentication method would work for that or if a dedicated feature would be better.

Thanks

**Comment by scheb** [comment]
Included in release v2.1.0
