### ISSUE TITLE
Support for multiple sites running one Symfony App <2.6

### ISSUE THREAD

**Issue by raul782** [scheb/two-factor-bundle#38]
While the two factor bundle enforces both sites to authenticate in two steps.
Is there a way I can customize the template based on the host parameter?

The workaround is to create a dynamic template in twig so it builds the right template (which is causing an infinite loop at this point) or create a generic template to support both sites.

**Comment by scheb** [comment]
Multiple apps within the same project is not really supported. You need to solve it in the template somehow. Make it based on the hostname or some other criteria that you can use to determine which app you're in.

**Comment by raul782** [comment]
@scheb Thanks, yeah, I solved it at the Twig level, it works now. Though, It'll be nice to support this in a "native" way.
