### ISSUE TITLE
Add optional two factor auth

### ISSUE THREAD

**Issue by fkrauthan** [scheb/two-factor-bundle#4]
Is there a way to let the user choice if he wanna use google authenticator and/or email authentication. So by default just username and password auth is enabled. But the user can decide if he wanna use two factor auth.

**Comment by BigShanJohn** [comment]
hello scheb, i am little bit confused on the method called to enable and disable  email auth : isEmailAuthEnabled ? can you show us little bit of how its work. do I need to set my db authCode to emty string to disable it and give it a value to enable it. please explain

**Comment by scheb** [comment]
`isEmailAuthEnabled` is there to give the user the ability to enable or disable the email authentication. If you want to let the user enable/disable it, you need a boolean field on your user entity and return its value. If you want to have it enabled per default, just return `true`.

**Comment by BigShanJohn** [comment]
Thanks, I have solved it.
