### ISSUE TITLE
I can't register a new authentication provider

### ISSUE THREAD

**Issue by godzillante** [scheb/two-factor-bundle#41]
I wrote a new authentication provider, called "multiple" because using it I can allow both google and email authentication. According to the [docs](https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/custom.md), to register it I should write something similar to:

    <service id="acme.two_factor.provider" class="%acme.two_factor.provider.class%">
        <tag name="scheb_two_factor.provider" alias="acme_two_factor" />
    </service>

This is my yml, which I'm pretty sure it's equivalent. (I also had it checked online on http://converter.rosstuck.com/ and manually by an expert Symfony user):

    services:
        multiple.two_factor.provider:
            class: AppBundle\Security\MultipleTwoFactorProvider
            arguments:
                ...
            tags:
                - { name: scheb_two_factor.provider, alias: multiple }

and this is my config.yml:

    scheb_two_factor:
        ...
            email: ...
            google: ...
            
            multiple:
                enabled: true
                template: security\twofactor\twofactor.html.twig

but when I read the new config, e.g. when cleaning the cache, I get an InvalidConfigurationException:
  Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  Unrecognized option "multiple" under "scheb_two_factor"

The only workaround so far was adding the following code to _vendor/scheb/two-factor-bundle/DependencyInjection/Configuration.php_, right below the `arrayNode('google')` definition, but I know it's a Bad Thing™:

    /* vendor/scheb/two-factor-bundle/DependencyInjection/Configuration.php:56 */

        ->arrayNode('multiple')
            ->addDefaultsIfNotSet()
            ->children()
                ->booleanNode('enabled')->defaultFalse()->end()
            ->scalarNode('template')->defaultValue('SchebTwoFactorBundle:Authentication:form.html.twig')->end()
            ->end()
        ->end()

The provider in itself works like a charm, I solved all of the other issues I encountered by overriding the bundle when needed by following Symfony official docs, but it seems that I have kind of lost a step now.

P.S.: I'm on Symfony 3 (3.0.4), but I'm sure it shouldn't represent a problem.

**Comment by scheb** [comment]
```
        multiple:
            enabled: true
            template: security\twofactor\twofactor.html.twig
```
doesn't belong under scheb_two_factor.

If you want to have configuration options for your own two-factor-provider class, you have to add them to your own bundle.

**Comment by godzillante** [comment]
Hi Scheb, thanks for your reply.

I understand, but what's the purpose of letting me register a new provider if I can't use it within the bundle?

Actually, I don't really need to configure it, but I don't know how to tell to scheb_two_factor: "here's my custom provider, use it" :-)

Alternatively, can you give me some hints on best practices for extending scheb_two_factor in a new bundle? I tried following the official Symfony docs ([here](http://symfony.com/doc/current/cookbook/bundles/override.html) and [here](http://symfony.com/doc/current/cookbook/bundles/inheritance.html)) but no luck.

**Comment by godzillante** [comment]
Hi Scheb,

I think I understood now. I had it explained by the Symfony expert I was talking about before.

When I register a new provider I can actually _use_ it right away. That doesn't mean I can automagically have a configuration entry under `scheb_two_factor` section.

Sorry for wasting your time.
