### ISSUE TITLE
Discussion: signed cookies for trusted computer

### ISSUE THREAD

**Issue by zerkms** [scheb/two-factor-bundle#50]
What about using some sort of signed cookies data (using the `framework.secret` by default or any other explicitly set secret) - eg: JWT/JWE instead of persisting storage?

This would save some db queries and simplify the bundle integration (less requirements for user entities).

Thoughts?

**Comment by scheb** [comment]
The problem I see with signed cookies is that you cannot revoke them server-side and someone could easily extend the expiration date of the cookie and the server would need to accept this.

**Comment by zerkms** [comment]
@scheb yep, so it can be an alternative integration path then.

> and someone could easily extend the expiration date

It makes no sense to set JWT/JWE token expiration before (or to be precise - different at all) the cookie expiration time. So expanding it will not help since the token would expire itself.

**Comment by scheb** [comment]
I made the JWT solution part of the upcoming 3.0 version. Check out the beta.
