### ISSUE TITLE
Discussion: using cryptographically strong random for code sent via email

### ISSUE THREAD

**Issue by zerkms** [scheb/two-factor-bundle#51]
```php
    protected function generateCode($min, $max)
    {
        return mt_rand($min, $max);
    }
```

I think it might be a good idea to use `random_int` instead.

**Comment by scheb** [comment]
Thanks for pointing that out. New release has been published.

**Comment by umpirsky** [comment]
I see we use [random_bytes](http://php.net/random_bytes) now, and it is PHP 7 only. Not sure how tests are passing.

**Comment by scheb** [comment]
We're using paragonie/random_compat as a fallback.

**Comment by umpirsky** [comment]
@scheb Oh so cool! Thanks for the quick response. :+1:
