### ISSUE TITLE
Before the trusted device is persisted it should first check if context allows to do so.

### ISSUE THREAD

**Issue by zerkms** [scheb/two-factor-bundle#64]
Currently the implementation (excerpt) in `\Scheb\TwoFactorBundle\Security\TwoFactor\Trusted\TrustedFilter` looks like

```php
if ($context->isAuthenticated() && $request->get($this->trustedName)) {
    $cookie = $this->cookieManager->createTrustedCookie($request, $user);
    $response->headers->setCookie($cookie);
}
```

It is prone to race condition (when trusted is disabled between requests) or when a user manually added a flag.

So it should additionally check for `$context->useTrustedOption()`.

**Comment by scheb** [comment]
@zerkms Would you please send me a PR for it (also add a test case please)? Thanks!

**Comment by zerkms** [comment]
Yep, I will do tomorrow
