### ISSUE TITLE
How to show QR code?

### ISSUE THREAD

**Issue by paulheijman** [scheb/two-factor-bundle#68]
First of all: thank you for the great bundle!

I'm able to use my own template for the Google Authentication code, but I don't know how to use the following code (from the docs) to show a QR code in this template:
```
$url = $container->get("scheb_two_factor.security.google_authenticator")->getUrl($user);
echo '<img src="'.$url.'" />';
```

Thanks in advance!

**Comment by scheb** [comment]
You fetch the service in the controller, get the image URL from it and pass the URL to a Twig template, where you can show the image.

**Comment by paulheijman** [comment]
Thank you for the quick answer. My problem is: in which controller?
I have a simple DefaultController with an indexAction and an adminAction, but the auth code template is rendered from something else (Google/TwoFactorProvider.php?).

**Comment by scheb** [comment]
The QR code is to quickly configure Google Authenticator in your phone. When the user has registered, they don't have two-factor authentication with Google Authenticator enabled yet. So you have to build some page into your members area, where users can enable two-factor authentication. When a user has enabled two-factor authentication with Google Authenticator, you can show them the QR code on the page, so they can scan it with their phone and add it to the GA app. In addition to it, you should also show the secret code, so they can type it manually into the GA app.

**Comment by paulheijman** [comment]
Ah, sorry my mistake! I thought the QR code was needed with every login... Thanks for your explanation!
