### ISSUE TITLE
Only Redirect Master Requests

### ISSUE THREAD

**Issue by sebastianblum** [scheb/two-factor-bundle#69]
hello,

We had big trouble with our template that uses ESI.
In my opinion, https://github.com/scheb/two-factor-bundle/blob/master/Security/TwoFactor/EventListener/RequestListener.php need a check, if it is a master request.

We have to discuss what we do with sub request in the meanwhile.

**Comment by scheb** [comment]
Closed in favor of #70.

**Comment by scheb** [comment]
The change caused more problems than it helped, see #71. Commits have been reverted in v2.8.1. Issue reopened.

**Comment by scheb** [comment]
I believe this issue should be solved in the 3.0 version, since it has proper firewall integration. If not, let me know.

**Comment by sebastianblum** [comment]
thank you @scheb - I will test it and provide an example app to reproduce.

**Comment by scheb** [comment]
@sebastianblum You may want to have a look at https://github.com/scheb/two-factor-app, that's the test application I'm using to test the bundle.

**Comment by sebastianblum** [comment]
great work @scheb -  I send you a pr for the test app. In my opinion, it works now.
