### ISSUE TITLE
Limiting to Master Request + Security Voter breaks the authentication form

### ISSUE THREAD

**Issue by scheb** [scheb/two-factor-bundle#71]
Release v2.7.0 (limiting the two-factor check only to master requests) may break 2FA, because a non-master request may invoke a security check, which triggeres the voter, which causes a security exception to rise (voter votes against access granted, because 2fa not yet complete). This prevents the authentication form from being shown.

Temporary solutions:
- Disable voter
- Use 2.6.x

**Comment by peschee** [comment]
Is this fixed in the latest 2.8 version?

**Comment by scheb** [comment]
No, please use either 2.6.x or disable the voter.

**Comment by peschee** [comment]
So versions >2.6.x don't work or they work differently (have to have the voter disabled)?

**Comment by scheb** [comment]
Depends on your setup, please try it out. I had a local Symfony 2.6 setup where I ran into problems with the change related to master requests and the voter. But so far no one else complained, so could also be an issue with my setup.

I created the issue to keep track of it and let people know who might run into the same problem.

**Comment by peschee** [comment]
If I update to 2.7 the two factor auth functionality breaks. The form for the auth code never displays. Instead, I get a 403 error.

**Comment by peternijssen** [comment]
Version 2.7 also breaks for me. I have a Symfony 3.1.4 set up with some voters. The form is never shown but an "access denied" message shows up.

**Comment by scheb** [comment]
Reverted the problematic commits, new release 2.8.1 should work without that issue.
