### ISSUE TITLE
Renew trusted cookie on login

### ISSUE THREAD

**Issue by SirWaddles** [scheb/two-factor-bundle#80]
I've been using this bundle in a production application for awhile now, and I noticed most users have ~30 trusted computer tokens each.

The cookie expires after a set time, but the token is kept in the database. When the user checks the box again, a new one is generated (users also find this frustrating because they log in regularly and at seemingly sporadic intervals are required to enter their two-factor code again)

Would it be a good idea to allow an option to resend the cookie with a new expiration date on a sucessful remembered login? This way, when a user is actively using an application, it will remember them for the entire duration but if they fall into absence, they will need to reauthenticate.

**Comment by scheb** [comment]
This is a feature of the upcoming 3.0 version. Check out the beta.
