### ISSUE TITLE
http-only trusted cookies

### ISSUE THREAD

**Issue by zerkms** [scheb/two-factor-bundle#82]
At the moment the trusted device cookie only accepts the lifetime and the secure flag.

How about adding the httponly additionally to that?

For discussion: would one treat having `httponly: true` as the new default value as a breaking change?

**Comment by scheb** [comment]
I think it would be fine to add the change. Can't really imagine a use-case that would break from that.

**Comment by zerkms** [comment]
Wait a second, it is already httponly :facepalm:

Sorry :-D
