### ISSUE TITLE
Is it possible to enable and disable the two-factor-bundle trough a Controller

### ISSUE THREAD

**Issue by Eviltoastey** [scheb/two-factor-bundle#83]
Hey!

I want my users to be able to enable or disable the Google two factor auth whenever they want.
Is it possible to change the "enabled" option in the config.yml in any way so the Google auth can be turned on or off?

Hope to hear from you soon :)!

**Comment by scheb** [comment]
Hello,
the preferred way would be to have a persisted boolean field in the user entity. Ff the user wants to enable/disable two-factor-authentication set the flag accordingly. Then, depending on the flag, you can return `null` or the secret code in the [getGoogleAuthenticatorSecret()](https://github.com/scheb/two-factor-bundle/blob/master/Model/Google/TwoFactorInterface.php) method.

**Comment by Eviltoastey** [comment]
Thanks for the tip!

I got it working now :)

Again thanks!! :D

**Comment by Eviltoastey** [comment]
Sorry for another (maybe stupid question).

In the defaultcontroller I can call:
$this->get("scheb_two_factor.security.google_authenticator")->generateSecret();

But in the User entity I can't call this, is there anyway to generate a secret in the user entity?

(I want to give every user a secret on registering )

Thanks again :)!

**Comment by scheb** [comment]
I'm no longer that deep in the Symfony framework stack, but there should be an event just before the user entity is persited to the database. You can register a listener to that event and inject the `scheb_two_factor.security.google_authenticator` service into the listener class. Then generate the secret and write it to the user entity.

Alternatively create the secret later, when the user enables two-factor-authentication.

**Comment by Eviltoastey** [comment]
The second option sounds like a solid sollution! 

Sorry for asking all these questions but thanks alot for your time :)!

Cheers!

**Comment by scheb** [comment]
No problem :)
