### ISSUE TITLE
$url not using the correct Secret

### ISSUE THREAD

**Issue by Eviltoastey** [scheb/two-factor-bundle#84]
When using $url = $this->get("scheb_two_factor.security.google_authenticator")->getUrl($user); it uses the wrong SECRET code. 

URL:
string(180) "https://chart.googleapis.com/chart?chs=200x200&chld=M|0&cht=qr&chl=otpauth%3A%2F%2Ftotp%2FKeliba%3Amarco%2540slik.eu%40Zioo%2520Keliba%3Fsecret%3DKKUGJP3N65XJ3VWQ%26issuer%3DKeliba" 

The secret Code:
string(16) "KKUGJP3N65XJ3VWQ"

As you can see the secret code is different from what the URL uses. 

it puts a 3D before the code.

Is there a fix for this? What am I doing wrong?

**Comment by scheb** [comment]
Too me it looks like "KKUGJP3N65XJ3VWQ" is exactly the string used in the URL. The %3D is an URL-encoded "=" character.

**Comment by Eviltoastey** [comment]
If I try to scan it Google says the code isnt recognized (The QR) but if I type it in manually it works.

**Comment by Eviltoastey** [comment]
Sorry for bothering I know where the fault is. I'm going to fix it now thanks for the help!
