### ISSUE TITLE
2factor when fosuserbundle password reset

### ISSUE THREAD

**Issue by Psarmidani** [scheb/two-factor-bundle#85]
Hi,

I have implemented 2factor and it works. But i have noticed that there isn't a 2factor authentication after resetting a password. I directly logged in after that.

Is there a way to implement the 2factor on password reset?

**Comment by scheb** [comment]
Does the FOS bundle actually log you in directly after resetting the password? If that's the case it's probably doing this in some weird way, that bypasses the events that you would normally get from the security layer and because of that the two-factor-bundle cannot react on it.

**Comment by Psarmidani** [comment]
Yes it does. So the secure way is to redirect the user to the login page instead of loggin the user directly?

**Comment by Psarmidani** [comment]
I solved this issue by redirecting a user to the login page after resetting the password.
So a user need to login again after that. This will trigger the tow-factor. 

Thank you for your help Scheb !
