### ISSUE TITLE
Cookie created does not consider SameSite

### ISSUE THREAD

**Issue by cordoval** [scheb/two-factor-bundle#92]
https://symfony.com/blog/new-in-symfony-3-2-httpfoundation-improvements

**Comment by scheb** [comment]
Hmm, should it be lax or strict? Or should we make it configurable?

**Comment by cordoval** [comment]
configurable

**Comment by scheb** [comment]
Available from release v2.11.0

**Comment by cordoval** [comment]
done on master

**Comment by cordoval** [comment]
you beast, congrats, great efforts done here 👴 good job! 👍

**Comment by cordoval** [comment]
something is wrong, it does not set Same-Site on my end, does it do it on your side? @scheb

**Comment by scheb** [comment]
Unfortunately I don't have a 3.2+ environment set up that I could use to reproduce it. Maybe if I find some time at the weekend. I checked the Cookie class parameter to make sure that I put it in the right position, but it looks good.

To make sure: Your HttpFoundation component is at 3.2 or higher, right? Could you check that the right value is passed into the TrustedCookieManager?

**Comment by cordoval** [comment]
I solved it, please close this

symfony does not really support samesite key on cookie yet, the component is the only one that supports it sort of but it does not really. I did get what I wanted though. And I am good with everything now.

So let's close it. It is a symfony problem to be resolved at symfony land or userland like i did.
