### ISSUE TITLE
proxy manager should probably be an optional dependency

### ISSUE THREAD

**Issue by iltar** [scheb/two-factor-bundle#95]
Heya,

I noticed that the proxy manager is added as "require", but from what I can find, the only reason of why it's added, is the `lazy="true"` in a few service definitions. I believe this dependency should be optional as I rather not have this dependency in my application, can this be safely removed to "require-dev"?

**Comment by cordoval** [comment]
yeah totally agree, 👍

**Comment by scheb** [comment]
Done

**Comment by cordoval** [comment]
https://github.com/scheb/two-factor-bundle/commit/df3ad5b0619661ca446356bdd78b41dee5038c4b
