### ISSUE TITLE
Integration with Symfony 3.3

### ISSUE THREAD

**Issue by pptasinski** [scheb/two-factor-bundle#97]
Sending emails not work

**Comment by scheb** [comment]
Sad to hear, but I'm not sure if it's the bundles fault, because the bundle is using the SwiftMailer service from Symfony framework and except they've changed something about that, it should work.

Does sending emails from your Symfony project work in general?

**Comment by pptasinski** [comment]
Hi Scheb ! Sorry for this issue.....my mail was blacklisted.......don't comment it ;-)
