### ISSUE TITLE
Possible to redirect to 2FA authentication?

### ISSUE THREAD

**Issue by ro0NL** [scheb/two-factor-bundle#98]
Hi,

We're facing an issue where the 2FA form is rendered on the current page, thus submitting to the current page.

However, our routing is configured rather strict; we enable POST where needed. This causes our app to trigger 405 Method not allowed, pretty much randomly.

Can you suggest something.. should we open up all routes for POST? Or just change your bundle logic where needed?

Thx!

**Comment by scheb** [comment]
This is a known issue, which cannot be fixed with the current implementation. See #36.

**Comment by ro0NL** [comment]
Great. I changed the form action to submit to a fixed route which allows POST.

Works for me :)

**Comment by scheb** [comment]
Ok, good. Thanks for understanding that I cannot fix it that easily.
